### ISSUE TITLE
Add theory background vignette

### ISSUE THREAD

**Issue by spedygiorgio** [ModelOriented/DALEX#101]
The dalex package is extremely useful for explaining ML model outputs. Neverthess having a more "theroetical background" theory could be use as standard reference for publications. Is it possible to have some paragraphs on say ceteris paribus plot, shap values,...?

**Comment by pbiecek** [comment]
Thank you, 
We are working on this. 
You will find longer descriptions here https://pbiecek.github.io/PM_VEE/
This cheat sheet  shows  in which chapter you will find descriptions for each method https://github.com/pbiecek/DALEX/raw/master/misc/cheatsheet_local_explainers.png

**Comment by pbiecek** [comment]
The methodological descriptions will be in https://pbiecek.github.io/PM_VEE/
