### ISSUE TITLE
DALEXverse 0.19.8 release summer 2019

### ISSUE THREAD

**Issue by pbiecek** [ModelOriented/DALEX#102]
# Integration

- [x] readability: vignettes
- [x] readability: NEWS
- [x] readability: DESCRIPTION
- [x] consistency: pkgdown website
- [x] consistency: entry at DrWhy.AI webpage

assigned: @pbiecek

# Code review

- [x] consistency: names of functions 
- [x] consistency: names of files
- [x] consistency: names of variables in functions (local and global)
- [x] length: functions
- [x] readability: code (comments, constructions)

assigned: @kasiapekala 

# Feature review

- [x] readability: documentation (title, description, details)
- [x] readability: examples (relevant, complete, with comments)
- [x] reproducibility: tests (code coverage)

assigned: @AdamIzdebski

**Comment by AdamIzdebski** [comment]
**Readability: documentation**
A lot of typos:
titanic: in the data set there are more variables declared (11) in the description that actually are in the data set imported (9). 
model_performance: little description what the function does, not consistent argument list, add link to explain function, 
plot(<explainer>): links to explainers that have created the input
HR: variable names
predict: description should be modified
plot: typo in arguments description, modify description 
loss_cross_entropy: documentation not consistent:function names, no description, argument descriptions not consistent with descriptions in other functions' documentation, could ba added a link to predict 

**Readability: examples**
explain: not consistent variable names in examples, example could be more informative
loss_function: optionally examples could be commented
model_performance: comment to the output

**Reproducibility: tests**
explain:add additional tests for different arguments default and present
add tests for yhat

**Comment by kasiapekala** [comment]
**consistency: names of files** 
misc.R could be renamed to helper_functions.R / utility_functions.R

**consistency: names of functions**
https://github.com/ModelOriented/DALEX/blob/master/R/explain.R#L16
shouldn't 'verbose' have the default set up the other way around? if verbose == TRUE, then it doesn't print out the text?

**consistency: names of variables in functions (local and global)**
ok

**length: functions**
https://github.com/ModelOriented/DALEX/blob/master/R/explain.R
explain.R

**lines much longer than 80 characters**
explain.R
loss_sum_of_squares, loss_root_mean_square, loss_accuracy (https://github.com/ModelOriented/DALEX/blob/master/R/loss_functions.R)
model_performance()
most plot.* functions have long first line

**readability: code (comments, constructions)**
https://github.com/ModelOriented/DALEX/blob/master/R/feature_response.R#L60
shouldn't the information about the deprecation of used method (like feature_response) be printed also when it's called without explainer?

https://github.com/ModelOriented/DALEX/blob/master/R/loss_functions.R#L42
= could be changed to -> (x, y, auc)

https://github.com/ModelOriented/DALEX/blob/master/R/plot_model_performance.R
https://github.com/ModelOriented/DALEX/blob/master/R/plot_prediction_breakdown.R
(almost) no code comments

https://github.com/ModelOriented/DALEX/blob/master/R/plot_variable_importance.R#L68
comments that probably should be removed

https://github.com/ModelOriented/DALEX/blob/master/R/plot_variable_response.R#L57
(not consistent) line wraping after every parameter

https://github.com/ModelOriented/DALEX/blob/master/R/theme_mi2.R#L9
comment that probably should be changed into issue and removed

https://github.com/ModelOriented/DALEX/blob/master/R/yhat.R#L91
maybe this could be printed out as a message for user?

https://github.com/ModelOriented/DALEX/blob/master/R/yhat.R#L138
fully commented out function - should it be here?

**misc:**
while loading package, there is a long output detailing creation of new explainers and one warning (randomForest and unique values)
no documentation for combine_explainers() and typo in it's description (complain -> combine)

**Comment by pbiecek** [comment]
on CRAN
