### ISSUE TITLE
Fix NA in titanic dataset

### ISSUE THREAD

**Issue by maksymiuks** [ModelOriented/DALEX#104]
Please change titanic dataset to one not contatining NA data. Some models does not support NA and it may cause problems. 
My proposition is to replace NA in column country to "unknown", NA in price by arithmetic mean of price in the same class, and NA in sibs/parch by 0.

**Comment by pbiecek** [comment]
@maksymiuks proposed solution:
I will add a new dataset `titanic_imputed` with imputed data. This way old examples remain still valid and we will have a dataset without NAs.

**Comment by maksymiuks** [comment]
Seems great for me.
