### ISSUE TITLE
Add new information to explainer

### ISSUE THREAD

**Issue by maksymiuks** [ModelOriented/DALEX#110]
explainer should know more about itself, for example if model is regression, binary classification or multilabel classification task.

**Comment by pbiecek** [comment]
see #109 
it should know the library name and version
```
explainer$model_info = list(package, type, version)
```

**Comment by pbiecek** [comment]
@maksymiuks it would be great to add this feature for the release fall 2019

**Comment by pbiecek** [comment]
Don in 67dafea
