### ISSUE TITLE
Fix "DALEX show-cases" (mlr, keras...) and add an information about DALEXtra

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/DALEX#111]
1. Recompile them for new plot looks 
2. Use ingredients/iBreakDown/auditor instead of DALEX deprecated? 
3. Use DALEXtra?

**Comment by pbiecek** [comment]
Suggestions: 
Let's do 2 and 3 later, we can alway create better documentation with new examples
The 1 shall be relatively easy, if something is not working, please put this information here, and we will either fix it or remove it. 
New points:
4. add `session_info()`
5. For mlr and h2o and possibly others add section 0. with **bold** with information that this can be done with `DALEXtra`

**Comment by pbiecek** [comment]
Thanks, fixed in https://github.com/pbiecek/DALEX_docs/pull/23
