### ISSUE TITLE
Error in modules$np$int32(x) : attempt to apply non-function In addition: Warning message:

### ISSUE THREAD

**Issue by asheetal** [ModelOriented/DALEX#125]
`explainer_keras_dalex <- DALEX::explain(model_keras,
                                        data = as.matrix(train_input_matrix),
                                        y = as.numeric(train_output_matrix),
                                        label = "Keras Model",
                                        predict_function = function(m,x) keras_predict(m, x, verbose=2))

vi_keras_dalex <- variable_importance(explainer_keras_dalex,
                                      #type = "difference",
                                      loss_function = loss_root_mean_square,
                                      n_sample = -1)

`

The above code was working fine on a few projects. Seems after an upgrade to some packages now I am getting errors and warning. Not able to figure out where is the issue. What has changed?

> 
> > Preparation of a new explainer is initiated
>   -> model label       :  Keras Model 
>   -> data              :  12456  rows  379  cols 
>   -> target variable   :  12456  values 
>   -> predict function  :  function(m, x) keras_predict(m, x, verbose = 2) 
>   -> predicted values  :  the predict_function returns an error when executed (WARNING) 
>   -> residual function :  difference between y and yhat (default)
>   -> residuals         :  the residual_function returns an error when executed (WARNING) 
> A new explainer has been created!
> > use type = "raw" for raw plotting
> > vi_keras_dalex <- variable_importance(explainer_keras_dalex,
>                                        #type = "difference",
>                                       loss_function = loss_root_mean_square,
>                                      n_sample = -1)
> Error in modules$np$int32(x) : attempt to apply non-function
> In addition: Warning message:

**Comment by pbiecek** [comment]
could you give an R code that reproduces the problem along with session_info?
