### ISSUE TITLE
Warnings when task i multilabel classification 

### ISSUE THREAD

**Issue by maksymiuks** [ModelOriented/DALEX#128]
Add warning that explainer with default yhat will take only one column as significant

**Comment by pbiecek** [comment]
ok, let's check first which explainers handle multilabel classification

- [ ] break_down
- [ ] shap
- [ ] ceteris_paribus
- [ ] feature_importance
- [ ] model_residuals
- [ ] model_performance
- [ ] funnel_plot

**Comment by maksymiuks** [comment]
So, model_residuals and model_performance don't work. In terms of feature_importance and funnel_plot, they will work if we provide accrodingly loss_function and score_function that handles multilabel classification. Rest is fine.

**Comment by maksymiuks** [comment]
Candidate fix https://github.com/ModelOriented/DALEX/commit/08763b54f2d9ae82163fdc061392b2d688b56eba

**Comment by maksymiuks** [comment]
I think it is done. Please check it out here https://github.com/ModelOriented/DALEX/blob/february_release/R/explain.R#L195-L197
--
