### ISSUE TITLE
move ingredients, iBreakDown etc. to Imports and use their print, plot functions

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/DALEX#132]

**Comment by pbiecek** [comment]
DALEX cannot import ingredients, because ingredients imports DALEX.
cyclic dependencies are not allowed.

will look for other solutions, either keep ingredients and iBreakDown as suggests (-> problem with plot() ) or move shared functions to another package (like color themes to DALEXutils, OMG)

**Comment by pbiecek** [comment]
ok, candidate solution is in the branch 
https://github.com/ModelOriented/DALEX/tree/DALEX_1_0_0

it looks like the print/plot functions from `ingredients`/`iBreakDown` are available even if these packages are only Suggested.

The `library(DALEX)` does not load `ingredients` directly (at leas is not visible via `loadedNamespaces()`),

But if any function from `ingredients` is called (e.g. after `DALEX::variable_importance`) then `ingredients` are loaded according to `loadedNamespaces()` and `plot/print` functions are working properly.

**Comment by pbiecek** [comment]
fixed in https://github.com/ModelOriented/DALEX/tree/DALEX_1_0_0
