### ISSUE TITLE
Rebuild yhat for parsnip and caret

### ISSUE THREAD

**Issue by maksymiuks** [ModelOriented/DALEX#142]
Rebuild yhat for parsnip and caret so they handle multilabel classification as, for instance, randomForest do.

**Comment by pbiecek** [comment]
There was a bug in `yhat.ranger`
For a single observation and the classification the output from the `predict` function was a vector not a matrix.
So the predict[,2] indexing was not working as expected.
I've fixed `yhat.ranger` with an additional `if nrows()==1` 

you may check parsnip and caret if they do not have similar problems.
