### ISSUE TITLE
Guidance on RNN

### ISSUE THREAD

**Issue by asheetal** [ModelOriented/DALEX#148]
Wondering if anyone has any guidance on trying on white-box explanations of RNN built on top of time-series data. There is a beautiful tutorial by @fchollet https://blogs.rstudio.com/tensorflow/posts/2017-12-20-time-series-forecasting-with-recurrent-neural-networks/

I want to take one step further and try to explain the keras RNN model. Any suggestions?

**Comment by pbiecek** [comment]
DALEXtra package has function that facilitate working with keras, see
https://modeloriented.github.io/DALEXtra/reference/explain_keras.html

@maksymiuks do we have other examples for keras models?

**Comment by maksymiuks** [comment]
@asheetal Here is a vignette that explains how to export the Python model (including keras nn) into R and explain them using DALEX. 
https://raw.githack.com/pbiecek/DALEX_docs/master/vignettes/How-to-use-DALEXtra-to-explain-and-visualize-scikitlearn-models.html

**Comment by pbiecek** [comment]
fixed in https://github.com/ModelOriented/DALEX/commit/6f24df0be652fb3281305d97e211520771ab0387
