### ISSUE TITLE
Discussion: model_parts n_sample and model_profile N

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/DALEX#175]
1. I would argue that `n_sample` in `model_parts` should be `NULL` like in `ingredients`.
https://github.com/ModelOriented/DALEX/blob/1a0c76812961f2770ad1a8f2b452870a00c5b91c/R/model_parts.R#L46

2. Maybe add a `message` saying that your 20k-row dataset is being cut to only 5%.

3. Maybe use fraction sampling. If so, consider changing the `N` in `model_profile` as well.

4. Unify `n_sample` and `N` into one argument, check if there are other functions using `n_sample`

**Comment by pbiecek** [comment]
I wonder if there is any significant difference between using 1k vs 20k rows for assessment of feature importance. If not then calculations for 1k will be much faster (and AFAIK now these calculations are repeated B times).

Yes, it is good idea to unify `n_sample_` and `N` if they occur in the same context.

**Comment by pbiecek** [comment]
is it fixed? can we close it?

**Comment by hbaniecki** [comment]
The name of `n_samples` parameter got changed in Python but remains the same in R.
