### ISSUE TITLE
Documentation for plotting feature importance/variable_importance

### ISSUE THREAD

**Issue by pinehowe** [ModelOriented/DALEX#176]
Hello,

I haven't been able to find any documentation on the plots for variable_importance. I think I am following what the default plot is doing based on the data.frame that is produced from variable_importance. The default plots don't seem to show the correct number of bars and I couldn't find any information on how to change the plots.

I think a broader request would be a vignette on plotting/ modifying the default plots since they all seem to be different and are not all represented in the documentation.

Thanks, love this package!

**Comment by hbaniecki** [comment]
Hi,
Thanks for reporting the issue. For now, you can use the documentation of the `ingredients` package https://modeloriented.github.io/ingredients/reference/plot.feature_importance_explainer.html

**Comment by marcjermaine-pontiveros** [comment]
@hbaniecki Thank you for pointing us the docs for iBreakDown, etc.! 
I don't know if this is helpful but I got this minor issue a while ago for binary classification models. 
The prediction for the positive cases works fine, but for negative cases the prediction becomes unreadable. 
![image](https://user-images.githubusercontent.com/37885260/80011740-d9de3700-84fe-11ea-82dd-591dbd25dc46.png)

adding vcolors to the generic plot function worked for me:
```
bd_glm <- variable_attribution(explainer_glm, 
                               new_observation = x_test[1,],
                               type="break_down")

bd_glm2 <- variable_attribution(explainer_glm,
                                new_observation = x_test[30,],
                                type="break_down")
bd_colors <- c("#f05a71","#4378bf", "#8bdcbe", "#ffa58c")

p1 <- plot(bd_glm2, vcolors = bd_colors)
p2 <- plot(bd_glm, vcolors = bd_colors)
```

![image](https://user-images.githubusercontent.com/37885260/80012035-45280900-84ff-11ea-94be-4a2e65ae4c0c.png)

Thanks for your reply!

**Comment by hbaniecki** [comment]
Indeed, this is a known issue. I will transfer it to the `iBreakDown` package.
