### ISSUE TITLE
Optimize pandas constructors in for loops

### ISSUE THREAD

**Issue by WojciechKretowicz** [ModelOriented/DALEX#186]
For example in shap, it seems that there could be achieved higher efficiency, replacing data frames with numpy arrays

**Comment by hbaniecki** [comment]
Maybe use parallel computing

**Comment by WojciechKretowicz** [comment]
I have added parallel computing. Optimization of constructors gave mediocre results and made code much harder to read, so will not be included in a package, at least at this moment.
