### ISSUE TITLE
python: how to use dalex using xgboost

### ISSUE THREAD

**Issue by frucci** [ModelOriented/DALEX#188]
Here some code:

```
import dalex as dx
import pandas as pd
import numpy as np
import xgboost as xgb
import warnings
warnings.filterwarnings('ignore')
```

```
data = dx.datasets.load_titanic()
X = data.drop(columns=["survived","embarked", "class", "gender"])
y = data.survived
```

```
dct_params = {}
dct_params["eta"] = .5
dct_params["min_child_weight"] = 50
dct_params["max_depth"] = 6
dct_params["subsample"] = .7
dct_params["colsample_bytree"] = .9
dct_params["lambda"] = 1
dct_params["alpha"] = 0
dct_params["objective"] = "binary:logistic"
dct_params["nthread"] = 5
dct_params["eval_metric"] = "auc"
```

```
xgb_train = xgb.DMatrix(X, label=y)
xgb_model_best = xgb.train(dct_params, xgb_train, verbose_eval=1)
```

Now is I use xgb_train as "data"

`exp = dx.Explainer(xgb_model_best, data=xgb_model_best, y=y, label="xgboost")`

I've got this error:

> Preparation of a new explainer is initiated
> 
>   -> label             : xgboost
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-24-8bbdf31e0a75> in <module>
> ----> 1 exp = dx.Explainer(xgb_model_best, data=xgb_model_best, y=y, label="xgboost")
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\dalex\_explainer\object.py in __init__(self, model, data, y, predict_function, residual_function, weights, label, verbose, precalculate, colorize, model_info, model_type)
>      66         """
>      67 
> ---> 68         data = check_data(data, verbose)
>      69 
>      70         # REPORT: checks for y
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\dalex\_explainer\checks.py in check_data(data, verbose)
>      25         data = pd.DataFrame(data)
>      26     elif not isinstance(data, pd.DataFrame) and data is not None:
> ---> 27         raise TypeError("data must be pandas.DataFrame or numpy.ndarray")
>      28     elif data is None:
>      29         verbose_cat("  -> data   : not specified!", verbose=verbose)
> 
> TypeError: data must be pandas.DataFrame or numpy.ndarray

using X as "data" instead:

`exp = dx.Explainer(xgb_model_best, data=X, y=y, label="xgboost")`

> Preparation of a new explainer is initiated
> 
>   -> label             : xgboost
>   -> data              : 2207 rows 4 cols
>   -> target variable   : Argument 'y' was a pandas.Series. Converted to a numpy.ndarray.
>   -> target variable   : 2207 values
>   -> predict function  : <function yhat_default at 0x0000021AE2F9E288> will be used
>   -> predicted values  :  the predict_function returns an error when executed
> 'DataFrame' object has no attribute 'feature_names'
>   -> residual function : difference between y and yhat
>   -> residuals         :  the residual_function returns an error when executed
> 'DataFrame' object has no attribute 'feature_names'
>   -> model_info        : package xgboost
> 
> A new explainer has been created!

How can i fix this?

**Comment by hbaniecki** [comment]
Hi,
I made a custom `predict_function` and it seems to work.
```python
def predict_xgb(model, data):
    return model.predict(xgb.DMatrix(data))

exp = dx.Explainer(xgb_model_best,
                              data=X,
                              y=y,
                              predict_function=predict_xgb,
                              label="xgboost")
```
We should add it to the package.

**Comment by frucci** [comment]
solved ty :)

**Comment by WojciechKretowicz** [comment]
New version 1.5 has been released to Pypi. It can handle xgboost now. Remember to pass data to explainer as a Data Frame. I will add example with it at dalex_docs this week.

Good luck!

**Comment by frucci** [comment]
ty
