### ISSUE TITLE
python: How to save plot programmatically

### ISSUE THREAD

**Issue by frucci** [ModelOriented/DALEX#190]
Hi, I'm sorry for the infra day double issue :)

I'm trying to save plots programmatically by using plt.savefig() but it is not working.
How can I do it?

**Comment by hbaniecki** [comment]
Hi,
Feel free to post more issues. This is how we know what to focus on.

Firstly, there is a possibility to save the plot with an icon in the top right corner.

I found success in saving `plotly` plots programmatically following [plotly instructions](https://plotly.com/python/static-image-export/). For now, the `plot` method is not returning the `fig` object so this is not possible. We should probably change that.

**Comment by frucci** [comment]
Yes,  I know I can save the picture using the icon but I was wondering to not show any pictures but just save .png files or something similar. I suppose you've already answered with "the plot method is not returning the fig object"

**Comment by hbaniecki** [comment]
@frucci in the next version you will be able to use `show=False` parameter in `plot` method to return the `plotly Figure` object.
