### ISSUE TITLE
python: data type not understood error

### ISSUE THREAD

**Issue by rabitwhte** [ModelOriented/DALEX#191]
Hi,

I'm getting 'data type not understood error' for code similar to the titanic example. I have reinstalled/updated packages. Also I created new anaconda environment etc. Nothing seems to work. The whole error:

---------------------------------------------------------------------------
>TypeError                                 Traceback (most recent call last)
><ipython-input-5-09824664c85b> in <module>
>----> 1 exp.predict_profile(x_example)
>
>~\AppData\Roaming\Python\Python36\site-packages\dalex\_explainer\object.py in predict_profile(self, new_observation, type, y, variables, grid_points, variable_splits)
>    194             )
>    195 
>--> 196         predict_profile_.fit(self, new_observation, y)
>    197 
>    198         return predict_profile_
>
>~\AppData\Roaming\Python\Python36\site-packages\dalex\instance_level\_ceteris_paribus\object.py in fit(self, explainer, new_observation, y)
>     38 
>     39         if not check_variable_splits(self.variable_splits, variables):
>---> 40             variable_splits = calculate_variable_split(data, variables, self.grid_points)
>     41 
>     42         y = check_y(y)
>
>~\AppData\Roaming\Python\Python36\site-packages\dalex\instance_level\_ceteris_paribus\utils.py in calculate_variable_split(data, variables, grid_points)
>     95     variable_splits = {}
>     96     for variable in variables:
>---> 97         if np.issubdtype(data.loc[:, variable].dtype, np.floating):
>     98             # grid points might be larger than the number of unique values
>     99             probs = np.linspace(0, 1, grid_points)
>
>~\.julia\v0.6\Conda\deps\usr\envs\XAI2\lib\site-packages\numpy\core\numerictypes.py in issubdtype(arg1, arg2)
>    391     """
>    392     if not issubclass_(arg1, generic):
>--> 393         arg1 = dtype(arg1).type
>    394     if not issubclass_(arg2, generic):
>    395         arg2_orig = arg2
>
>TypeError: data type not understood

Code:

![image](https://user-images.githubusercontent.com/43826606/79363338-1088e000-7f48-11ea-8baf-cccb78c1aa74.png)

**Comment by hbaniecki** [comment]
Hi,
Can you provide code that I can copy and paste to check this problem?

**Comment by hbaniecki** [comment]
@rabitwhte can you check:
```python
for variable in variables:
    print((data.loc[:, variable].dtype, np.issubdtype(data.loc[:, variable].dtype, np.floating)))
```

**Comment by rabitwhte** [comment]
Got it. One of the columns was categorical. Thank you very much for your quick help.
