### ISSUE TITLE
Add more parameters to model_performance

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/DALEX#194]
Like in Python. It makes using this function a lot easier in many cases.
![image](https://user-images.githubusercontent.com/32574004/79454498-a164c780-7feb-11ea-97b7-f985790ec7ba.png)
By default its `NULL` and extracts the information from the explainer.

**Comment by maksymiuks** [comment]
Is that really necessary? We currently have field `type` in the explainer object as well as `model_info$type`. It can be extracted from there.

**Comment by hbaniecki** [comment]
For me, this parameters are not useful at all. Only when I have to use `model_performance()` it makes a difference, and then I am forced to change the `explainer` object, which is not convenient.

**Comment by hbaniecki** [comment]
`model_prediction` or `Explainer.predict` both have the `data` parameter. It would be nice to have `data` parameter in `model_performance` to easily calculate `train` and `test` performance measures.

**Comment by pbiecek** [comment]
I think that both `data` and `label` is an argument that can be accepted by any function for explanation (`model_parts` and so on). 
If it is not given, nothing happens, and 
if it is given, the data (using update_data/update_label) is replaced by that given in the function. 
This will make it easier to draw and compare training test data.
Same applies to the `type`.

But if we are going to do this consistently it sounds like a long term feature.

**Comment by hbaniecki** [comment]
Sidenote: the `type` parameter in dalex is named `model_type` since `model_performance` (and others) has `type` already. Also (1) `type` in explainer doesn't mean that much (2) `model_info$type==model_type` makes more sense

**Comment by pbiecek** [comment]
Is is still open?

If yes, then I would not modify `model_performance` (too much changes, as we need to do the same with `model_parts` and others
instead let's add `update_model_info` function that modify the model_info field in the explainer

**Comment by hbaniecki** [comment]
Using `update_model_info` will be harder than using `type` in `explain`. The whole purpose of this issue was to make `model_performance` easier to use as in Python.

**Comment by pbiecek** [comment]
true, but it is too much changes in function signatures at this point.
If it is not critical, let's postpone it for `DALEX 2.0`

**Comment by hbaniecki** [comment]
Adding new argument is not even breaking backward compatibility.

**Comment by hbaniecki** [comment]
Ok
