### ISSUE TITLE
R: subtitle for model_parts is centering

### ISSUE THREAD

**Issue by kozaka93** [ModelOriented/DALEX#196]
Subtitle for model_parts is centering
```
library(DALEX)

no <- titanic_imputed[1,]

m1 <- glm(survived~. , data = titanic_imputed)
e1 <- explain(m1, titanic_imputed, titanic_imputed$survived, label = "glm")
fi <- model_parts(e1)

plot(fi)
```

![obraz](https://user-images.githubusercontent.com/24189252/79642619-fd238200-819e-11ea-81c6-43070d605486.png)

Thanks

**Comment by pbiecek** [comment]
thanks, it's a problem with `ingredients:::plot.feature_importance_explainer` which overrides the `theme(plot.subtitle)`

**Comment by pbiecek** [comment]
Thanks

fixed in https://github.com/ModelOriented/ingredients/commit/5108a1050a6d7cafbfe2c2c11a61787ea0c55524
