### ISSUE TITLE
Discussion: default for loss_function in model_parts

### ISSUE THREAD

**Issue by kasiapekala** [ModelOriented/DALEX#202]
I've noticed different results of `feature_importance` in DALEX and ingredients. It is caused by different default values for loss_function. I was wondering shouldn't they be the same for consistency reasons.

https://github.com/ModelOriented/DALEX/blob/8858926c4abb5b7cd7d1a16bfd9f6df2434003b0/R/model_parts.R#L43

https://github.com/ModelOriented/ingredients/blob/9f8f82f05ddb87e4abf2fb20846f097113522a33/R/feature_importance.R#L152

```
> library("DALEX")
> model_titanic_glm <- glm(survived ~ gender + age + fare,
                         data = titanic_imputed, family = "binomial")
> explain_titanic_glm <- explain(model_titanic_glm,
                               data = titanic_imputed[,-8],
                               y = titanic_imputed[,8])

> DALEX::feature_importance(explain_titanic_glm, n_sample = NULL) 
      variable mean_dropout_loss label
1 _full_model_          370.1496    lm
2        class          370.1496    lm
3     embarked          370.1496    lm
4        sibsp          370.1496    lm
5        parch          370.1496    lm
6          age          371.6003    lm
7         fare          384.4722    lm
8       gender          548.2130    lm
9   _baseline_          599.7132    lm

> ingredients::feature_importance(explain_titanic_glm)
      variable mean_dropout_loss label
1 _full_model_         0.4095316    lm
2        class         0.4095316    lm
3     embarked         0.4095316    lm
4        sibsp         0.4095316    lm
5        parch         0.4095316    lm
6          age         0.4101522    lm
7         fare         0.4173782    lm
8       gender         0.4976695    lm
9   _baseline_         0.5178448    lm

> ingredients::feature_importance(explain_titanic_glm, loss_function = DALEX::loss_sum_of_squares)
      variable mean_dropout_loss label
1 _full_model_          370.1496    lm
2        class          370.1496    lm
3     embarked          370.1496    lm
4        sibsp          370.1496    lm
5        parch          370.1496    lm
6          age          371.0894    lm
7         fare          384.0622    lm
8       gender          546.5614    lm
9   _baseline_          598.0323    lm
```
(Because of https://github.com/ModelOriented/DALEX/issues/175, `n_sample = NULL` in `DALEX::feature_importance`)

**Comment by pbiecek** [comment]
Thank you. It's a tricky one.
I like the default in ingredietns (unit as in target variable), but any change in DALEX will affect the existing code. Let's change this in DALEX 2.0.

**Comment by hbaniecki** [comment]
change `plot.model_performance()` parameter `lossFunction` to `loss_function`

**Comment by maksymiuks** [comment]
I think it is related to https://github.com/ModelOriented/ingredients/issues/117

**Comment by pbiecek** [comment]
any propositions how to solve this?

I'm ok with: do not touch `ingredients`
let the default `loss_function` in `model_parts` be NULL
and in this case let `model_parts` decide which loss function shall be used (based on `model_info`)

**Comment by hbaniecki** [comment]
Why not let ingredients decide?

**Comment by maksymiuks** [comment]
What about putting that last change to `ingredients`? Setting default loss_function to `NULL` and then recognizing proper withing `feature_importance.explainer()`. We can address loss function from DALEX via '::' as it is done now. Such change will not affect existing code, so backward compatibility will be maintained. Then not only `model_parts` use proper `loss_function` bot for the instance `modelStudio` as well.

**Comment by pbiecek** [comment]
I wouldn't change the default behavior of two packages. (see discussion on slack). This way we can keep stable ingredients and elastic frontend (DALEX)

**Comment by maksymiuks** [comment]
Well, then I guess the only valid solution is to make DALEX and any other package that imports feature importance (ie. modelStudio) check type on its own.

**Comment by hbaniecki** [comment]
So the idea is to implement this function in `ingredients` and use it in other packages?

**Comment by maksymiuks** [comment]
From what I've understood the idea is not to touch ingredients and let for example to DALEX setting proper function. If someone uses `ingredients` explicitly then default loss function is till rmse. Am I correct @pbiecek ?

**Comment by hbaniecki** [comment]
I meant to implement `ingredients::switch_loss_function` that can be used in other packages, not only `DALEX`.

**Comment by pbiecek** [comment]
Currently `DALEX` depends on `ingredients`, 
thus to solve most problems we shall add the `switch_loss_function` to `ingredients` (`modelStudio` and `arenaR` do not depend on `DALEX` but depend on `ingredients`).

**But**  the `switch_loss_function` will not be used in `ingredients` (not to change the default behaviour. It will be used in DALEX to change default behaviour of `model_parts` and `model_performance`.

**Comment by maksymiuks** [comment]
model_performance does not need `switch_loss_function` because its behaviour depends not only on loss_function. We need to distniguish the type within the function in order to apply proper measures.

**Comment by pbiecek** [comment]
I've added `loss_default` to the DALEX.

In the first iteration I've added it to `ingredients` but then I could not assume that every user will have ingredients in v 1.3. So it was safer to put it in DALEX.
If this function is needed in modelStudio or arena I think it can be safely copied.

```
> loss_default
function(x) {
  # explainer is an explainer or type of an explainer
  if ("explainer" %in% class(x))  x <- x$model_info$type
  switch (x,
          "regression"     = loss_root_mean_square,
          "classification" = loss_one_minus_auc,
          "multiclass"     = loss_cross_entropy,
          stop(x, " is not recognized as task name")
  )
}
```

**Comment by pbiecek** [comment]
Problem with this approach is that `model_parts()` does not know which loss function is selected
