### ISSUE TITLE
explainer.predict_parts does not work correctly with numpy array data

### ISSUE THREAD

**Issue by tmakowski** [ModelOriented/DALEX#207]
I have encountered an error in Python version of the package. It happend while using data which was numpy arrays - `X_train` being a matrix and `y_train` a vector. When trying to call method `predict_parts` on the explainer I have gotten following error:
![image](https://user-images.githubusercontent.com/38053499/80152739-8500f600-85bc-11ea-9b80-b7b835c5a72c.png)

Clearly the `X_train[0, :]` is a `numpy.ndarray` while the error message suggests it is not. The model used was `ExtraTreesClassifier` from `sklearn.ensemble`.

I have tried the same with data being pandas dataframes and it worked just fine:
![image](https://user-images.githubusercontent.com/38053499/80152820-aa8dff80-85bc-11ea-8e07-49b0313f330d.png)

**Comment by hbaniecki** [comment]
Hi,
Thanks for the notice. Indeed, I see the inconsistency here.

https://github.com/ModelOriented/DALEX/blob/84550e0c05765575083ddb269c51860cc038c8ea/python/dalex/dalex/instance_level/_break_down/checks.py#L16

https://github.com/ModelOriented/DALEX/blob/84550e0c05765575083ddb269c51860cc038c8ea/python/dalex/dalex/instance_level/_shap/checks.py#L12

https://github.com/ModelOriented/DALEX/blob/84550e0c05765575083ddb269c51860cc038c8ea/python/dalex/dalex/instance_level/_ceteris_paribus/checks.py#L19

**Comment by hbaniecki** [comment]
fixed in #209
