### ISSUE TITLE
CeterisParibus.plot doesn't work for integer new_observation.index

### ISSUE THREAD

**Issue by niko989** [ModelOriented/DALEX#211]
Hi, 

I have an error for a while now and I am not able to fix it...

Basically I try to do ceteris-paribus plots, similar to those in your titanic jupyter notebook:
cp_mary.plot(cp_john)

Your titanic notebook works well for me.  However, I work with a different, but similar dataset.
I get the following error for a while now, but I am not sure to fix it. It is because of the '_ids_' variable.

Invalid value of type 'numpy.int64' received for the 'name' property of scatter
        Received value: 1

    The 'name' property is a string and must be specified as:
      - A string
      - A number that will be converted to a string

lib\site-packages\dalex\instance_level\_ceteris_paribus\object.py in plot(self, objects, variable_type, variables, size, color, facet_ncol, show_observations, title, horizontal_spacing, vertical_spacing, show)
    187                         showlegend=False,
    188                         name=df.iloc[0, df.columns.get_loc('_ids_')],
--> 189                         row=row, col=col
    190                     )
    191 

The predict_profile method works well.
Maybe you can help me. 
Regards,
Niko

**Comment by hbaniecki** [comment]
Hi,
Thanks for the feedback. This will be fixed in the next version.

**Comment by niko989** [comment]
Ok thank you a lot!
