### ISSUE TITLE
Xgboost model. Predict function returns an error.

### ISSUE THREAD

**Issue by zlotopolscylover** [ModelOriented/DALEX#214]
We have a problem with creation of an explainer with package dalex. We are dealing with uplift modeling. We calculate uplift based on function calc_uplift_filled, which is based on xgboost model. Our xgboost model has been trained on np.array and we would like to keep it that way. As you can see on the attached screenshot predict function returns an error. Can you advise us some workaround?
<img width="723" alt="issue_dalex" src="https://user-images.githubusercontent.com/56076270/80865588-ca8f8400-8c8a-11ea-86fa-143f61d5867e.PNG">

**Comment by hbaniecki** [comment]
Hi,
What is the output of:
```js
calc_uploft_filled(r_xgb_model, X_train)
```

**Comment by hbaniecki** [comment]
TODO: inform the user that `data` is converted to `pd.DataFrame` https://github.com/ModelOriented/DALEX/blob/ce0839fb88c77308832098be5aff4fbf3aa775a5/python/dalex/dalex/_explainer/checks.py#L30

**Comment by zlotopolscylover** [comment]
> 
> 
> Hi,
> What is the output of:
> 
> ```js
> calc_uplift_filled(r_xgb_model, X_train)
> ```
> 
> Also, can you try converting `x` into desired `numpy`/`xgboost.DMatrix` type in `calc_uplift_filled`? `X_train` will be converted to `pd.DataFrame` after passing it to `Explainer`.

We followed the recommendation and did a mapping to np.array in calc_uplift_filled and the explainer worked - thanks, but now there is a new problem. We have an error in the model_profiles function.

<img width="713" alt="issue_dalex_2" src="https://user-images.githubusercontent.com/56076270/80893028-149a5900-8ccf-11ea-94d0-93879afbfa83.PNG">

**Comment by hbaniecki** [comment]
From this screenshot, I can't even see where the problem occurred in `dalex`. Can you provide a reproducible example that I can run?

**Comment by zlotopolscylover** [comment]
We are still struggling with running dalex explainations on xgboost model trained on np.array.
It seems that the problem is in array conversion to dataframe inside dalex. As you know the package better we hope you can tell as what exactly we should change.

This is a link to our repository - we would like to run the pdp file.
[https://github.com/ludziej/IML-historical-marketing-campaign](url)

**Comment by hbaniecki** [comment]
Reproducible meaning that I can run it, preferably in the form of `jupyter-notebook`. 

`pyhon pdp.py` yields some `HDF5 library` errors that I won't be able to resolve.

**Comment by zlotopolscylover** [comment]
Here is the link to google colab jupyter-notebook with reproducible example.

[https://colab.research.google.com/drive/1krREix2XdCNJzowUjYiEKG1eX_9nf126#scrollTo=N2VzyR0FKzls](url)

**Comment by zlotopolscylover** [comment]
https://colab.research.google.com/drive/1krREix2XdCNJzowUjYiEKG1eX_9nf126#scrollTo=N2VzyR0FKzls

**Comment by hbaniecki** [comment]
@zlotopolscylover Thanks for this catch! Your example works on the soon-to-be-merged `dalex` version.
