### ISSUE TITLE
model_profile bugs when task is multiclass classification

### ISSUE THREAD

**Issue by maksymiuks** [ModelOriented/DALEX#222]
When creating plots (both, partial and accumulated)  using `model_profile()` bad things happen do colors. 

```
library(randomForest)
mod <- randomForest(Species~., data=iris)
library(DALEX)
me <- explain(mod, data=iris, y = iris$Species)
mp <- model_profile(me) 
plot(mp)
```

Replacing the value of `mp$color` with `"_laabel_"` fixes that issue.

```
mp$color <- "_label_" 
plot(mp)
```

But there is still a warning when executing it.

**Comment by pbiecek** [comment]
`mp$color <- "_label_" ` does not solve the problem
