### ISSUE TITLE
MultiIndex, discussion

### ISSUE THREAD

**Issue by WojciechKretowicz** [ModelOriented/DALEX#224]
Is it good idea to return data frames with multiindex instead of a plain ones? For example in ALE, if you group by `['gender', 'embarked']` index could be: `('label', 'gender', 'embarked', 'variable_name')`.

There is no index usage in dalex at this moment and labels can get ambiguous if more than one group is applied.

**Comment by hbaniecki** [comment]
Closing this issue and adding it to https://github.com/ModelOriented/DALEX/projects/1 as it is unlikely to happen in the near future
