### ISSUE TITLE
Modify values in `predict_parts_break_down`

### ISSUE THREAD

**Issue by franckess** [ModelOriented/DALEX#227]
Hi team,

Say I have the following:

![image](https://user-images.githubusercontent.com/7226560/82288218-57ee0a80-99e5-11ea-8aec-c6c6b9e00800.png)

All values on the **breakdown chart** are `log-scaled` (i.e. to get the actual values, one would need to apply the $e^x$).

How do I modify the `predict_parts_break_down` to do that in `R`?

**Comment by hbaniecki** [comment]
Hi,
I think that a custom `predict_function` is an answer to your question. Here is some code: 
```r
library(DALEX)

data <- apartments
data$m2.price <- log(data$m2.price)

model <- lm(m2.price~., data=data)

pf <- function(model, data) {
  exp(predict(model, data))  
}

explainer <- explain(model, 
                     data = data,
                     y = exp(data$m2.price),
                     predict_function = pf)

bd <- predict_parts(explainer, data[1,])
plot(bd)
```

**Comment by franckess** [comment]
Awesome, thanks
