### ISSUE TITLE
The change from n.sample to N and the difference between CRAN and GH complicates development of other tools

### ISSUE THREAD

**Issue by pbiecek** [ModelOriented/DALEX#229]
EMA, triplot and mlr3book are victims of changes in the name of the parameters. Authors can use arguments under CRAN knowing that it will soon generate varnishes, or use the GH version knowing that it does not work with CRAN.

Suggested solution: abandon the warnings and allow the use of both N and n_sample at the same time.

**Comment by hbaniecki** [comment]
Isn't a CRAN release a solution to this?

**Comment by pbiecek** [comment]
I was hoping for this, but it is not a solution.

- We shouldn't release 1.3 because there were too many changes and this version needs some time before release.
- Currently, some of the material is co-created by people who may not be willing to update packages too often, each dependency update causes something else that used to work may stop working (through changes in ggplot2 or base R).
(It's not a theory, it's happening)

**Comment by hbaniecki** [comment]
sidenote: comment out the `lossFunction` warning too
