### ISSUE TITLE
R: Check class of y when residual and predict functions are default

### ISSUE THREAD

**Issue by maksymiuks** [ModelOriented/DALEX#231]
Right now we don't have proper check for `y` if deafult predict and residual functions were passed. It may cause misinformation among our users, who will don't know  why DALEX does not work. First of all warning https://github.com/ModelOriented/DALEX/blob/master/R/explain.R#L169-L173 should appear only for the classification and regression tasks. For multiclass this warning is FALSE since y has to be a factor for that type of task. We should have warnings for all accepted task types ie. "regression", "classification" and "multiclass" if `y` with the wrong class was passed. By wrong, I mean other than  "numeric", "numeric 0,1" and "factor" accordingly.

**Comment by pbiecek** [comment]
@maksymiuks is it still an issue?

**Comment by pbiecek** [comment]
close due to the lack of response

**Comment by maksymiuks** [comment]
Candidate fix in #308
