### ISSUE TITLE
Problem when plotting aggregated profiles

### ISSUE THREAD

**Issue by maksymiuks** [ModelOriented/DALEX#237]
Following code causes an error:

```
library(gbm)
library(DALEX)
model <- gbm(m2.price~., data = apartments, distribution = "gaussian")
explainer_1 <- explain(model, data = apartments, y = apartments$m2.price, label = "explainer_1")
explainer_2 <- explain(model, data = apartments, y = apartments$m2.price, label = "explainer_2")
adp_1 <- model_profile(explainer_1, variables = "surface")
adp_2 <- model_profile(explainer_2, variables = "surface")

plot(adp_1, adp_2)
```

and it occurs there https://github.com/ModelOriented/ingredients/blob/master/R/plot_aggregated_profiles.R#L85-L86

I think something like this should solve that problem
```
dfl <- laaply(dfl, function(x) {
if (class(x) == "model_profile") {
ret <- x$agr_profiles
} else {
ret <- x
}
x
})

**Comment by hbaniecki** [comment]
https://github.com/ModelOriented/ingredients/issues/122

**Comment by pbiecek** [comment]
Thanks, I will check this in few days while working on PDP chapter for EMA

**Comment by pbiecek** [comment]
imho it's not an error
the recommended way of plotting few profiles in a single plot in EMA is
```
plot(adp_1$agr_profiles, adp_2$agr_profiles)
```
and this works.

**Comment by hbaniecki** [comment]
Let's add this example to the documentation (and more viable examples from EMA to the DALEX documentation).
