### ISSUE TITLE
Eval metrix calculated with model_performance() differ from those with caret::confusionMatrix()

### ISSUE THREAD

**Issue by FrieseWoudloper** [ModelOriented/DALEX#250]
I'd like to compare a decision tree with a random forest, So I first trained a decision tree and calculated some evaluation measures on a test set using `caret::confusionMatrix()`. I did the same using the `DALEX` package. Although the trees and predictions are the same, the metrics (precision, recall, F1) calculated by `model_performance()` differ from those calculated with `caret::confusionMatrix()`. Why is this? Am I doing something wrong? 
See: https://rpubs.com/friesewoudloper/630778

**Comment by hbaniecki** [comment]
Hi,  I believe that`caret` uses `0` as the positive class and `DALEX` uses `1` as the positive class.

**Comment by pbiecek** [comment]
@maksymiuks can we take care about this in the default predict function?

**Comment by maksymiuks** [comment]
It is, but the solution would require modification of the input model (adding an attribute in explainer function)

**Comment by hbaniecki** [comment]
Why not in `model_performance`?

**Comment by pbiecek** [comment]
imho either explainer or predict function should know which label is positive

**Comment by maksymiuks** [comment]
Let's focus on it after DALEX 2.0.0 release.

**Comment by maksymiuks** [comment]
Solved in #353
