### ISSUE TITLE
Differences in results (measures) from randomForest and model_performance

### ISSUE THREAD

**Issue by ManuelSpinola** [ModelOriented/DALEX#252]
I am wondering why are differences in measures from randomForest and model_performance?

regr_rf <- randomForest(m2.price~., data = apartments)

regresar_rf
Call:
 randomForest(formula = m2.price ~ ., data = apartments) 
               Type of random forest: regression
                     Number of trees: 500
No. of variables tried at each split: 1

          Mean of squared residuals: 82639.43
                    % Var explained: 89.94

explainer_regr_rf <- DALEX::explain(regr_rf, label="rf", data = apartments, y = apartments$m2.price)

mp <- model_performance(explainer_regr_rf)

mp

Measures for:  regression
mse      : 38401.13 
rmse     : 195.9621 
r2       : 0.9532416 
mad      : 117.8836

Residuals:
         0%         10%         20%         30%         40%         50% 
-391.699706 -204.432248 -153.299826 -111.689600  -71.032887  -37.060230 
        60%         70%         80%         90%        100% 
   1.948415   52.362420  134.996121  255.409313  897.276892

**Comment by hbaniecki** [comment]
Hi, here is some code:
```r
library(DALEX)
library(randomForest)

set.seed(123)
regr_rf <- randomForest(m2.price~., data = apartments)
regr_rf # Mean of squared residuals: 81369.99

y <- apartments$m2.price

# conventional error
y_hat <- predict(regr_rf, apartments)
mse <- mean((y-y_hat)^2)
mse # 37671.22

# out-of-bag error
y_hat_oob <- predict(regr_rf)
mse_oob <- mean((y-y_hat_oob)^2)
mse_oob # 81369.99
```
This is because the `randomForest` package calculates it in a different way. See:
- https://stats.stackexchange.com/a/455854
- https://stats.stackexchange.com/a/369217
- https://stackoverflow.com/a/30809819

**Comment by ManuelSpinola** [comment]
Thank you very much.
