### ISSUE TITLE
Issue with variable_attribution : contrasts can be applied only to factors with 2 or more levels

### ISSUE THREAD

**Issue by anks7190** [ModelOriented/DALEX#254]
Hi , I am  getting - > contrasts can be applied only to factors with 2 or more levels error while running variable_attribution.
I have an idea that this error generally comes , when either a character/ factor variable has less than 2 levels but I have checked that all my categ variables have more than 1 levels. 
PS: I have trained Xgboost for classification . 

Thanks

**Comment by maksymiuks** [comment]
Hi

Could You please show a code sample that generates the mentioned error? It would be way easier to help then.

**Comment by pbiecek** [comment]
@anks7190 do you still need a hand?
if so, would you share a reproducible example that rises an error?

**Comment by anks7190** [comment]
Hi @pbiecek  , apologies for not updating with this issue .
Actually , I figured out the error . It was due to one of the categorical variable having just 1 level in the dataset on which the model was fitted.

**Comment by pbiecek** [comment]
Thanks!
