### ISSUE TITLE
DALEX could not find function "variable_response"

### ISSUE THREAD

**Issue by alasaa** [ModelOriented/DALEX#258]
hi, 
Whatever method I use to build the model (I have  tried "xgboost", "carte" and "mlr"), it seems that Whenever I try to use DALEX package, R always prompts the same Error :
Error in variable_response(...) : could not find function "variable_response"

Following is my code (R 3.5.0):
#
source("https://bioconductor.org/biocLite.R")
biocLite("DALEX")

library("breakDown")
head(wine)
library("xgboost")
model_martix_train <- model.matrix(quality ~ . - 1, wine)
data_train <- xgb.DMatrix(model_martix_train, label = wine$quality) 

param <- list(max_depth = 2, eta = 1, silent = 1, nthread = 2,objective = "reg:linear")
wine_xgb_model <- xgb.train(param, data_train, nrounds = 50)
wine_xgb_model

library("DALEX")
explainer_xgb <- explain(wine_xgb_model, data = model_martix_train, y = wine$quality, label = "xgboost")
explainer_xgb
sv_xgb_satisfaction_level <- variable_response(explainer_xgb, variable = "alcohol", type = "pdp")

Error in variable_response(explainer_xgb, variable = "alcohol", type = "pdp") : 
  could not find function "variable_response"
#
# I also tried this:
sv_xgb_satisfaction_level <- DALEX::variable_response(explainer_xgb, variable = "alcohol", type = "pdp")
Error: 'variable_response' is not an exit object in 'namespace:DALEX'

I also tried to manually download the "DALEX_1.3.0.zip" package from the web page (https://cran.r-project.org/web/packages/DALEX/index.html) and install it through the RStudio, but the same Error still occurred when I ran the above code.

Did I do something wrong?

Besides, I know a "variable_response()" of "survxai", however the explainer built via survxai (have "Times") is different with explainer bulit via DALEX. So I can not use "survxai::variable_response" either. I also tried to find the original code of variable_response() of DALEX, but I only found variable_response() of survxai.

I have tried to solve it as best I could, but I'm still stuck here. What should I do, please.

Thank you very very much.
alasaa

**Comment by martinnnuez** [comment]
variable_response() function is not working for me, i am trying to explain a model that it has been done using the h2o package.
Any help wold be very much apreciated.

**Comment by hbaniecki** [comment]
Hi,
The `variable_response()` function name has changed to `model_profile()`. Does that resolve your issue?

**Comment by martinnnuez** [comment]
Yes!!, it also works, i found variable_effect(), and done it that way.
Thank you very much!!

Enviado desde Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by alasaa** [comment]
Thanks a lot!  It works.
