### ISSUE TITLE
DALEX & tidymodels

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/DALEX#265]
ref https://github.com/tidymodels/planning/issues/11

**Comment by maksymiuks** [comment]
Solved in DALEXtra. We can close

**Comment by pbiecek** [comment]
thanks 
will keep this open as we should prepare sone nice document with examples how to use DALEX(tra) with tidymodels

**Comment by hbaniecki** [comment]
@maksymiuks can we close this?

**Comment by maksymiuks** [comment]
@hbaniecki closing

**Comment by jacekkotowski** [comment]
Can this be somehow related? 
https://github.com/ModelOriented/rSAFE/issues/10
