### ISSUE TITLE
'order' parameter in 'predict_parts' can be longer than the number of variables

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/DALEX#272]
This behaviour looks inconsistent. Shouldn't the `order` parameter consider only variables (and not interactions that are unseen to the user)? Also, we could use a check for the `order` parameter.

![image](https://user-images.githubusercontent.com/32574004/88411498-54597400-cdd8-11ea-950b-759ef18708af.png)

**Comment by pbiecek** [comment]
These indices refer to a matrix in which first p rows are for single variables and remaining p(p-1)/2 are for pairs of variables.

In R one can select these rows by numeric indices or by names, thus it can be 
`order = c("attacking_crossing:weight_kg", "height_cm")` or `order = c(7, 2)`. 
Fist is easier to use, second requires more knowledge about internals.

**Comment by hbaniecki** [comment]
Sure, the question was if the user should be able to pass interactions in the `order` parameter (e.g. `order=['age:gender']`), so I can fix the documentation.

**Comment by pbiecek** [comment]
This is how the R version works, not sure about the Python one

**Comment by hbaniecki** [comment]
Thanks, it works the same.
