### ISSUE TITLE
Dependencies: Imports package versions

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/DALEX#281]
Shouldn't the `DESCRIPTION` file enforce the newest `ingredients` and `iBreakDown` package versions? E.g. `predict_profile` now uses `variable_splits_type='uniform'` which exists only in the newest `ingredients` version `v1.3.1`.

**Comment by pbiecek** [comment]
maybe not newest, but it should expect version that is in fact required by DALEX.
so for DALEX 1.4 we can require ingredients and iBreakDown 1.3.1 (as there are some patches in DALEX but currently there are no changes in other packages)
