### ISSUE TITLE
variables_groups() function

### ISSUE THREAD

**Issue by zhengjiji456** [ModelOriented/DALEX#283]
Hi,

I updated the package DALEX to the newest version and tried the function "variable_groups()" using the codes you provided as examples. It worked. The results showed the importance of the grouped variables. However, when I tried this function with my model and data, it failed to show the grouped variables but the separated ones. The codes showed below:

library(caret)
library(DALEX)

model_test10<-train(
  Skewness ~ altitude + DIN3 + mean_10 + pca.climate.pc1 + pca.climate.pc2 + pca.climate.pc3 + pca.soil.pc1 + pca.soil.pc2 + pca.soil.pc3 + pca.landscape_10km.pc1 + pca.landscape_10km.pc2 + pca.landscape_10km.pc3,
  data.final.machine10,
  method = "rf",
  trControl = trainControl(
    method = "repeatedcv",
    number = 10,
    repeats = 100,
    verboseIter = TRUE
  )
)

model_explainer_test10 <- explain(model_test_final10, label="Random Forest", data = data.final.machine10[,-1], y = data.final.machine$Skewness)

model_vi_rf_test10 <- feature_importance(model_explainer_test10, loss_function = loss_root_mean_square,
                                                B = 100,variables_groups = list("A" = "altitude",
                                                                         "F" = "mean_10",
                                                                         "N" = "DIN3",
                                                                         "C" = c("pca.climate.pc1","pca.climate.pc2","pca.climate.pc3"),
                                                                         "S" = c("pca.soil.pc1","pca.soil.pc2","pca.soil.pc3"),
                                                                         "L" = c("pca.landscape_10km.pc1","pca.landscape_10km.pc2","pca.landscape_10km.pc3")))

#results showed below, not grouped variables

> model_vi_rf_test10
                 variable mean_dropout_loss         label
1            _full_model_        0.04108564 Random Forest
2  pca.landscape_10km.pc2        0.04407987 Random Forest
3            pca.soil.pc3        0.04558431 Random Forest
4  pca.landscape_10km.pc3        0.04619491 Random Forest
5                 mean_10        0.04627668 Random Forest
6            pca.soil.pc1        0.05038829 Random Forest
7            pca.soil.pc2        0.05587756 Random Forest
8                altitude        0.07872844 Random Forest
9  pca.landscape_10km.pc1        0.09623707 Random Forest
10        pca.climate.pc1        0.18344250 Random Forest
11                   DIN3        0.23480445 Random Forest
12        pca.climate.pc2        0.36471411 Random Forest
13        pca.climate.pc3        0.85595050 Random Forest
14             _baseline_        0.91902905 Random Forest

**Comment by hbaniecki** [comment]
Hi, 
Which example are you talking about? The parameter in the `feature_impotance` function is named `variable_groups` (without `s`). 
See https://modeloriented.github.io/ingredients/reference/feature_importance.html

**Comment by zhengjiji456** [comment]
Hi,

Thanks for your quick response.
That is my fault, I used the "variables_groups". Please close this issue.
