### ISSUE TITLE
relative importance of variables 

### ISSUE THREAD

**Issue by zhengjiji456** [ModelOriented/DALEX#299]
Hi,
![Fig_RF_skewness_1km](https://user-images.githubusercontent.com/21077143/90970174-f08bad80-e533-11ea-9134-a8f61e4dbc15.png)
I prepared this figure, but I am not sure what are the exact meanings of these bars.  May I interpreted this figure just like a box-plot with the median, Q1, and Q2?

Thanks

**Comment by hbaniecki** [comment]
@zhengjiji456 One can remove the boxplots using `show_boxplots=FALSE`. See https://modeloriented.github.io/ingredients/reference/plot.feature_importance_explainer.html
