### ISSUE TITLE
prediction_breakdown for linear model with splines

### ISSUE THREAD

**Issue by rdenham** [ModelOriented/DALEX#31]
Hi,
    just wondering how easy it would be to allow `prediction_breakdown` to work with a linear model when you use a spline term in the predictor. Here is my example:

```
apart.lm <- lm(m2.price ~ ns(construction.year, df=5) + surface + floor + no.rooms + district,
               data=apartments)
aplm.ex <- explain(apart.lm, data=apartmentsTest[, 2:6], y = apartmentsTest$m2.price)
new_apartment <- apartmentsTest[1,]
aplm.bd <- prediction_breakdown(aplm.ex, observation=new_apartment)
```

Gives the error:

```
Error in `[.data.frame`(new_observation, colnames(ny)) : 
  undefined columns selected
```

I guess I could take the `ns` part out and use the generated basis function, but it would be convenient if you didn't have to do this, particularly if you wanted to compare, eg, models with different basis functions.

Robert

**Comment by pbiecek** [comment]
Thanks, 
It is a general issue how to handle variable transformations specified in the model formula
In the first step I will add support for the `recipe` package, as it allows for tracking of variable preprocessing steps. 
Currently the dirty trick would be to call model.matrix directly to generate a data with new variables, but I will work on something more convenient.

**Comment by pbiecek** [comment]
should work after changes in iBreakDown v 1.0
