### ISSUE TITLE
deprecated functions

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/DALEX#313]
Consider removing `single_variable` with the release of `v2.0`.
https://github.com/ModelOriented/DALEX/blob/8859abc5dd0a40a4eeae3195b5b3286a22568781/R/model_profile.R#L110-L120

Add deprecation to `variable_effect` (use `DALEX::model_profile`).
https://github.com/ModelOriented/DALEX/blob/8859abc5dd0a40a4eeae3195b5b3286a22568781/R/model_variable_effect.R#L43-L49

Consider adding deprecation to more aliases (if not now then never).

**Comment by pbiecek** [comment]
adding deprecation to `variable_effect` is a very good idea.

but I will not remove any function now, let's do this after the release
(I know people that are using `single_variable`)
