### ISSUE TITLE
Keras models always have predict_proba & Warning: Sequential.predict_proba (from tensorflow.python.keras.engine.sequential) is deprecated and will be removed after 2021-01-01

### ISSUE THREAD

**Issue by WojciechKretowicz** [ModelOriented/DALEX#321]
Keras models have always `predict_proba` method, so explainer classifies them as classification models.

**Comment by hbaniecki** [comment]
Potential fix: `if model.predict_proba(data) returns error` set `model_type` to regression

Also: check for `Keras` model attributes for things like scikit-learn `_estimator_type`

**Comment by hbaniecki** [comment]
This is more complicated: Keras will only use `predict` method from `01/2021`
See: deprecated https://www.tensorflow.org/api_docs/python/tf/keras/Sequential#predict_proba
https://www.tensorflow.org/api_docs/python/tf/keras/Sequential#predict_classes
https://www.tensorflow.org/api_docs/python/tf/keras/Sequential#predict

**Comment by WojciechKretowicz** [comment]
solved
