### ISSUE TITLE
how to text print feature_importance result

### ISSUE THREAD

**Issue by asheetal** [ModelOriented/DALEX#328]
I am running code
```
    vi_dalex <- feature_importance(explainer_keras_dalex,
                                                 loss_function = loss_root_mean_square)
    plot(vi_dalex)
    vi_dalex
```
the plot is fine. However, I am interested in porting the output from vi_dalex to an excel. The text output is in increasing order while the plot is in decreasing order. Is there a way to grab the text report from feature_importance? There are thousands of predictors in my model and the most important is very difficult to reach in text output. I want to text dump top 50 features

**Comment by maksymiuks** [comment]
Yea, it is possible.

In general fi object stores result for all permutations that have been performed. therefore in order to get aggregated scores we need to extract permutation labeled as `0`. It can be done with the following code

```
library(DALEX)
model <- ranger::ranger(m2.price~., data = apartments)
explainer <- explain(model, apartments, apartments$m2.price)
fi <- model_parts(explainer)
print(fi)

fi[order(fi[fi$permutation == 0,]$dropout_loss, decreasing = TRUE),]
```

**Comment by asheetal** [comment]
Thank you for such a fast response. I see you chose permutation == 0. Would the answer be different if I do permutation == 1?
Is the plot using permutation == 0?

**Comment by maksymiuks** [comment]
As I said, `permutation == 0` extracts aggregated values over all permutations (for guidance over permutational feature importance see https://pbiecek.github.io/ema/featureImportance.html), and yes, those are values used by the plot function. ` permutation == 1` would grant You access to results of just one, the first, permutation.

**Comment by hbaniecki** [comment]
Just for the clarity: 
- the output of `model_parts`/`feature_importance` is `data.frame`
- the plot has boxplots that mark values for all permutations (turn off with `show_boxplots=FALSE`)
```r
library(DALEX)
model <- ranger::ranger(m2.price~., data = apartments)
explainer <- explain(model, apartments, apartments$m2.price)
fi <- model_parts(explainer)
class(fi)  # has data.frame

x <- as.data.frame(fi)
print(x)  # normal df

plot(fi)  # all permutations

plot(fi, show_boxplots=FALSE)  # only mean
```

**Comment by asheetal** [comment]
Thank you for the detailed explanation. Now I understand the purpose of show_boxplots. I will follow this in my next paper.
