### ISSUE TITLE
Add native support for more frameworks

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/DALEX#332]
- [x] scikit-learn API
- [x] tensorflow
- [x] xgboost
- [x] ~pyspark mllib~ (no contributors)
- [x] ~torch~ (probably undoable since the model can be anything)
- [x] pycaret (these are `scikit-learn` compatible through `finalize_model(model_only=False)`)
- [x] h2o
- [x] catboost (there is no conversion from `Pool` to `numpy`/`pandas` when categoricals are involved)

**Comment by keith12345** [comment]
Is there a plan to support h2o in python? Could that be added to this list?

**Comment by hbaniecki** [comment]
@keith12345 are we talking about these models? https://docs.h2o.ai/h2o/latest-stable/h2o-py/docs/modeling.html#supervised

**Comment by keith12345** [comment]
@hbaniecki Yup. [h2o random forest](https://docs.h2o.ai/h2o/latest-stable/h2o-py/docs/modeling.html#h2orandomforestestimator), [h2o GLM](https://docs.h2o.ai/h2o/latest-stable/h2o-py/docs/modeling.html#h2ogeneralizedlinearestimator), and [h2o XGBoost](https://docs.h2o.ai/h2o/latest-stable/h2o-py/docs/modeling.html#h2oxgboostestimator) specifically.

**Comment by hbaniecki** [comment]
These docs seem to fail for me:
```python
import h2o 
boston = h2o.import_file("https://s3.amazonaws.com/h2o-public-test-data/smalldata/gbm_test/BostonHousing.csv")
titanic = h2o.import_file("https://s3.amazonaws.com/h2o-public-test-data/smalldata/gbm_test/titanic.csv")
...
```
Could u provide any reproducible example?

**Comment by hbaniecki** [comment]
@keith12345 could you use: 
`pip install git+https://git@github.com/ModelOriented/DALEX.git@python-h2o#subdirectory=python/dalex`
and check if it works for you? 

notebook with basic examples: [h2o.zip](https://github.com/ModelOriented/DALEX/files/5593152/h2o.zip)

**Comment by keith12345** [comment]
@hbaniecki It's lookin' good! Although, I did catch one bug with ceteris_paribus using the titanic dataset (see attached). I saw that it worked in the notebook you provided. Looks like numpy is assuming the wrong type somewhere and that's causing the error.
[dalex-titanic-h20.zip](https://github.com/ModelOriented/DALEX/files/5593775/dalex-titanic-h20.zip)

**Comment by hbaniecki** [comment]
Thanks.

It is actually a bug in input, not in `dalex` - an observation has `class = '1st'`, while the `h2o` titanic dataset has `class` column coded as numbers. Also, mind that for classifiers `h2o` needs a factor, while `dalex` will need a numeric input. Clarifying your example: [dalex-titanic-h2o-works.zip](https://github.com/ModelOriented/DALEX/files/5595636/dalex-titanic-h2o-works.zip) 

Will add a proper notebook for `dalex+h2o` before this is released on `pip`.
