### ISSUE TITLE
Vignettes are not builded by pkgdown

### ISSUE THREAD

**Issue by pbiecek** [ModelOriented/DALEX#334]
There are no vignettes in the website created with pkgdown
https://modeloriented.github.io/DALEX/#

maybe it's related with https://github.com/ModelOriented/DALEX/blob/master/.Rbuildignore
(we do not ship vignettes to CRAN)
but we should have some solution to keep vignettes in the website with documentation

**Comment by hbaniecki** [comment]
I see two vignettes with plots on the site.

**Comment by pbiecek** [comment]
thanks, you are right,
it must have been a problem with something else
