### ISSUE TITLE
Logical values in y rise unnecessery warning

### ISSUE THREAD

**Issue by maksymiuks** [ModelOriented/DALEX#336]
We should change the warning for the classification task so it does not show up for logical values of `y`.

**Comment by pbiecek** [comment]
@maksymiuks it's WARNING

**Comment by pbiecek** [comment]
and please add labels for future reference

**Comment by pbiecek** [comment]
and what would be the best solution?
neglect WARNIG or maybe convert y to numeric values and add NOTE that y was automatically converted

**Comment by maksymiuks** [comment]
Both solutions are acceptable. On the one hand for numerical operations, logical vectors are treated as {0, 1} numeric but there may be a problem if something changes in the behavior of R core. On the other hand, converting logical to numerical with a NOTE may misslead some of the users.

**Comment by maksymiuks** [comment]
Do we have any conclusion?

**Comment by pbiecek** [comment]
@maksymiuks as you suggested, 
I think that it is safer to convert logical y into a numerical y in the `explain()` function with `as.numeric()`
and add a NOTE to the output of the `explain()` function.

this way all dependent functions can assume that y is numeric.

**Comment by pbiecek** [comment]
fixed in https://github.com/ModelOriented/DALEX/commit/458856f57ca9aa84959112a6600cb38edb12aff7
