### ISSUE TITLE
Save explainer to pickle

### ISSUE THREAD

**Issue by kozaka93** [ModelOriented/DALEX#339]
Hi, thanks for the great dalex package in Python.

I was working on a regression model and tried to save the explainer to pickle.  I have this error.

![obraz](https://user-images.githubusercontent.com/24189252/95622015-f5200d00-0a72-11eb-915e-e4584411e2e4.png)

I'm attaching the code with my example.

```
import dalex as dx
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
import pickle
data = dx.datasets.load_apartments()
data = pd.get_dummies(data)
X = data.drop(columns='m2_price')
y = data.m2_price
regr = RandomForestRegressor(max_depth=2, random_state=0)
regr.fit(X, y)
exp = dx.Explainer(regr, X, y)
pickle.dump(regr, open("model.pickle", "wb" ))
pickle.dump(exp, open("explainer.pickle", "wb" ))
```

**Comment by hbaniecki** [comment]
Hi,

There is an `Explainer.dump` method that saves the explainer to pickle. It removes the `residual_function`; thus, obeys the error.
