### ISSUE TITLE
model_diagnostics() - plotting residuals runs very long with 430K training instances

### ISSUE THREAD

**Issue by konradsemsch** [ModelOriented/DALEX#341]
Hi,

first of all, thanks for a great package and book - really a big fan of your work!

Coming to the question - I have run an explainer on a LightGBM model with 432920 instances of training data. When I want to inspect the residuals I first run:

```python
res = explainer_test.model_diagnostics()
```

which takes very little to complete, but when I then want to create any plot e.g.:

```python
res.plot(variable = "ids", yvariable = "residuals")
```

it takes between 20-30 minutes to complete. Do you also see a similar behaviour in your tests?

**Comment by hbaniecki** [comment]
Hi,

great question actually. The answer is: plotting the residuals takes seconds to complete. What runs very long is fitting the smoothing line, which `plotly` fits using the `statsmodels` package. 

`res.plot(smooth=False)` omits the problem. Enclosing a test: [plotly_500k.zip](https://github.com/ModelOriented/DALEX/files/5370075/plotly_500k.zip)

The other fix that I could propose is sampling the data before producing the `Explainer`.

**Comment by hbaniecki** [comment]
Should we sample the data, when `smooth=True`..
[The bottleneck:](https://github.com/plotly/plotly.py/blob/36013228bc2a99d96cc924dc104982819a9f51da/packages/python/plotly/plotly/express/_core.py#L316)
```python
import statsmodels.api as sm
sm.nonparametric.lowess(res.result.y_hat, res.result.residuals, missing="drop")
```

**Comment by konradsemsch** [comment]
Right, that makes sense - thanks for answering!

I also have another, more general question(s) regarding using DALEX/ DrWhy adjacent packages:

1) Is DALEX supposed to be a top level handler of all the adjacent DrWhy packages, providing effectively all their functionalities or are users actually supposed to use these underlying packages directly? Could you shortly elaborate on the target workflow?

2) What's the recommended path when working with a Python model? DALEX package is offered in both languages, but I think most other adjacent packages are mainly written in R.

**Comment by hbaniecki** [comment]
I believe that the target workflow is best described by the [figure on drwhy.ai](https://github.com/ModelOriented/DrWhy/blob/master/README.md#the-drwhyai-family) and in the [EMA book](https://pbiecek.github.io/ema/). 
`DALEX` R package main functionalities are:
- model adapter - the `explain()` function,
- vital explanations - most are a specific use of functionalities from the [ingredients](https://github.com/ModelOriented/ingredients) and [iBreakDown](https://github.com/ModelOriented/iBreakDown) packages.

The adjacent DrWhy packages extend these functionalities (may be independently developed, have extended dependencies) and are for the users to suit their needs. Most notably: 

- [auditor](https://github.com/ModelOriented/auditor) for model validation, error analysis
- [modelStudio](https://github.com/ModelOriented/modelStudio) for interactive Explanatory Model Analysis
- [fairmodels](https://github.com/ModelOriented/fairmodels) for bias detection and mitigation
- [arenar](https://github.com/ModelOriented/ArenaR) for exploration and comparison of models
- [vivo](https://github.com/ModelOriented/vivo) for alternative model-agnostic variable importance

The [DALEXtra](https://github.com/ModelOriented/DALEXtra) package allows creating model adapters for various ML frameworks, even for Python pickled models - this should be a safe bet e.g. for explaining `scikit-learn` models. 

Although for me, the current path when working with a Python model is creating the `Explainer` object using the `dalex` Python package, dumping it to the pickle file (see `dump/dumps` method), and finally loading the object into R using the [reticulate](https://github.com/rstudio/reticulate) package - [Example of Python+R DrWhy integration: lightgbm + dalex + modelStudio](https://modelstudio.drwhy.ai/articles/ms-r-python-examples.html#lightgbm-dashboard). Currently, an error occurs in `TensorFlow/Keras` dumping, as these models have a hard time being pickled.

Finally, we aim to make the `dalex` Python package a complete solution. This is why we plan to add other modules, which will incorporate the key functionalities from the `arenar, fairmodels, vivo` R packages into Python.

Should you lack more resources I would recommend following our [Responsible ML blog](https://medium.com/responsibleml).

**Comment by konradsemsch** [comment]
Thanks again for taking the time to write this comprehensive explanation! 

I'll follow your recommended approach of pickling the model and then performing the analysis in R. Will circle back in case I face any issues.
