### ISSUE TITLE
No difference between break-down plot for additive attributions and that for interactions

### ISSUE THREAD

**Issue by FrieseWoudloper** [ModelOriented/DALEX#343]
I was wondering why I don't see any difference between my break-down plot for additive attributions and my break-down plot for interactions.

```
library(DALEX)
library(ranger)
train <- titanic_imputed
set.seed(1234)
titanic_rf <- ranger(survived ~ ., data = train,
                     classification = TRUE, probability = TRUE)
exp_rf <- explain(titanic_rf,
                  data = train[, 1:7],
                  y = train$survived,
                  label = "Random Forest")
lucy <- data.frame(
      class = factor("1st", levels = c("1st", "2nd", "3rd",
                     "deck crew", "engineering crew",
                     "restaurant staff", "victualling crew")),
      gender = factor("female", levels = c("female", "male")),
      age = 18, sibsp = 0, parch = 0, fare = 70,
      embarked = factor("Southampton", levels = c("Belfast",
                        "Cherbourg","Queenstown","Southampton")))

bd_lucy <- predict_parts(exp_rf, lucy, type = "break_down")
plot(bd_lucy)

bd_lucy_order <- predict_parts(exp_rf, lucy, type = "break_down",
                               order = c("age", "gender", "fare", "class",
                                         "parch", "sibsp", "embarked"))
plot(bd_lucy_order)

bd_lucy_int <- predict_parts(exp_rf, lucy, type = "break_down_interactions")
plot(bd_lucy_int)
```

`bd_lucy` is different from `bd_lucy_order` due to model interactions, I assume.
So I expected `bd_lucy` to also be different from `bd_lucy_int`, but this isn't the case.
What am I overlooking?

**Comment by hbaniecki** [comment]
Hi, 

The `interaction_preference` scaling factor can enforce the use of interactions.
See:
-  https://pbiecek.github.io/ema/iBreakDown.html 
> Interactions are often weak and their net effects are not larger than the contributions of individual variables. If we would like to increase our preference for interactions, we can use the interaction_preference argument. The default value of  1
  means no preference, while larger values indicate a larger preference.
- https://modeloriented.github.io/iBreakDown/reference/local_interactions.html

```r
bd_lucy_int <- predict_parts(exp_rf, lucy, type = "break_down_interactions", interaction_preference=10)
plot(bd_lucy_int)
```
![image](https://user-images.githubusercontent.com/32574004/96497576-2fe02d00-124b-11eb-9991-89af81b40787.png)

**Comment by FrieseWoudloper** [comment]
Thank you for the clarification!
