### ISSUE TITLE
parallelizing feature_importance

### ISSUE THREAD

**Issue by asheetal** [ModelOriented/DALEX#348]
Currently it takes 1-2 days to run feature_importance built using Keras-GPU. Wish there was a way to parallelize it on multiple GPU or something and speed it up

**Comment by hbaniecki** [comment]
What is your data dimension? I would suggest changing `B` parameter to `1` and using your preferred parallel framework to compute single permutational importances. Then averaging the results.

**Comment by asheetal** [comment]
Thanks for quick response. My dataset is about 350K rows and about 1000 columns. Takes about an hour to train on Cuda but takes days to get feature_importance. Will try with B=1. Is there any code snippet available? I guess to achieve 10 runs, I will have to do 10/nGPU and then average. True?

**Comment by hbaniecki** [comment]
Exemplary code: 
```r
library("DALEX")
library("ranger")

model <- ranger(survived ~ .,
                            data = titanic_imputed, probability=T)
explainer <- DALEX::explain(model,
                            data = titanic_imputed[,-8],
                            y = titanic_imputed[,8])

results <- list()
for (i in 1:15) { # do this in parallel
  
  # N - number of observations to sample from data
  # B - number of permutation rounds
  # variables - vector of variables to calculate feature importance
  #             NULL is all (default)
  
  temp <- model_parts(explainer, N=1000, B=1, variables=NULL)
  temp$B <- temp$permutation <- i
  results[[i]] <- temp
}

result <- do.call(rbind, results)
as.data.frame(result) # what we see
 
library(dplyr) # NOTE: overrides DALEX::explaine

# average the permutations
avg_result <- result %>%
  group_by(variable) %>%
  summarize(dropout_loss = mean(dropout_loss, na.rm=TRUE),
            B = 0, label = explainer$label, permutation = 0) %>%
  as.data.frame()
avg_result$B <- 0

# merge and plot
fi <- rbind(result, avg_result)
plot(fi)
plot(fi, show_boxplots=FALSE)
```

With 1000 columns we can suspect, that there are a lot of correlated variables. These can be grouped into aspects (feature importance will be calculated for the whole group) - see the `triplot` package https://modeloriented.github.io/triplot 

Finally, there is also an alternative way of calculating the importance based on Partial Dependence Profiles. It has a high potential to be faster (since we only compute PDP and estimate their variance) - see the `vivo` package https://modeloriented.github.io/vivo

**Comment by hbaniecki** [comment]
I believe that there are no near plans of adding parallelization to `feature_importance` (moreover on GPU).
