### ISSUE TITLE
model_parts: Error in colnames(data) : argument "data" is missing, with no default

### ISSUE THREAD

**Issue by oleknow** [ModelOriented/DALEX#357]
I encountered an error in the model_parts function. Model (in scikit-learn) and DALEX explainer were created in Python. Then I packed explainer to pickle and loaded it in R. Object class is correct (dalex._explainer.object.Explainer), and function model_performance also gives correct response. However, another functions (model_parts, model_profile) return error:
_Error in colnames(data) : argument "data" is missing, with no default_.

Example taken from https://cran.r-project.org/web/packages/modelStudio/vignettes/ms-r-python-examples.html
```
import dalex as dx
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from numpy import log
data = dx.datasets.load_fifa()
X = data.drop(columns=['overall', 'potential', 'value_eur', 'wage_eur', 'nationality'], axis=1)
y = log(data.value_eur)
X_train, X_test, y_train, y_test = train_test_split(X, y)
model = Pipeline([('scale', StandardScaler()), ('svm', SVR())])
model.fit(X_train, y_train)
explainer = dx.Explainer(model, data=X_test, y=y_test, label='scikit-learn')
explainer.dump(open('explainer_scikitlearn2.pickle', 'wb'))

```
R script:
```
library(reticulate)
library(DALEX)
explainer <- py_load_object("explainer_scikitlearn2.pickle", pickle = "pickle")
performance <- model_performance(explainer)
parts <- model_parts(explainer)
```

`Error in colnames(data) : argument "data" is missing, with no default
`

**Comment by hbaniecki** [comment]
It is because the loaded `explainer` doesn't have the `'explainer'` class.

```r
class(explainer)
class(explainer) <- c(class(explainer), "explainer")
model_parts(explainer)
```

May I ask, why not use the `explainer.model_parts()` method in Python?

**Comment by hbaniecki** [comment]
@maksymiuks maybe we should add this `load_explainer` function into `DALEXtra`, what do you think?

**Comment by oleknow** [comment]
I would like to create dashboard for Python's model with DALEX visualizations. At the moment I feel better at R Shiny than e.g. in Dash/Bokeh. That's why I pickled model and loaded it to R. 
Workaround is okay, thank you for quick response!
