### ISSUE TITLE
conda Python package

### ISSUE THREAD

**Issue by RoyalTS** [ModelOriented/DALEX#360]
It would be great if one could install the Python version of DALEX using conda instead of having to use pip. Is this in the making?

**Comment by hbaniecki** [comment]
Agreed, I will look into it.
https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html

**Comment by hbaniecki** [comment]
Hi @RoyalTS, I have uploaded the package to conda https://anaconda.org/hbaniecki/dalex

```bash
conda config --append channels hbaniecki
conda install dalex
```

**Comment by hbaniecki** [comment]
Let's use https://conda-forge.org/docs/user/ci-skeleton.html and actually upload it to the organization level.

**Comment by hbaniecki** [comment]
Done: https://anaconda.org/conda-forge/dalex

@RoyalTS feel free to test this out. Let's open a new issue if any problems occur.
