### ISSUE TITLE
TypeError: 'predict_function' not compatible with the 'shap' package

### ISSUE THREAD

**Issue by pa-blan** [ModelOriented/DALEX#371]
Hi, is there a possibility to use a model with a preprocessing pipeline for 

model_parts(type='shap_wrapper', shap_explainer_type="TreeExplainer") in a Classification Explainer? 

`TypeError: 'predict_function' not compatible with the 'shap' package`

**Comment by hbaniecki** [comment]
The `shap` package introduced a new API for model-agnostic Explainer not so long ago in [v0.36](https://github.com/slundberg/shap/releases). I believe that this (+ support for Pipelines) is a work in progress, so I would restrain from adding it into `dalex` for now.

**Comment by pa-blan** [comment]
Thank you for your answer.  I have another question about catboost. Is there a reason why dalex does not support catboost for shap? 

```
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(test_X)
shap_plot = shap.summary_plot(shap_values, test_X, show=show,)
```

**Comment by hbaniecki** [comment]
I believe, that there is a `shap_explainer_type="TreeExplainer"` parameter that overrides any defaults/supports. Not sure why we didn't include catboost - will add. The list of models is growing anyway. I will look into `shap` after the stable changes.

**Comment by hbaniecki** [comment]
Feel free to contribute: https://github.com/ModelOriented/DALEX/blob/f7830004037e1a773a8f6304784bf7ad3e9ae4c2/python/dalex/dalex/wrappers/_shap/checks.py#L17-L21

**Comment by pa-blan** [comment]
@hbaniecki I think it's not a problem with the default settings. 

with:
`test = explainer.model_parts(type='shap_wrapper', shap_explainer_type="TreeExplainer") `
I get:
`AttributeError: 'TreeEnsemble' object has no attribute 'values'`

But with:
```
explainer = shap.TreeExplainer(catboost)
shap_values = explainer.shap_values(X_test)
shap_plot = shap.summary_plot(shap_values, X_test)
```
I get the plot.

**Comment by hbaniecki** [comment]
Got it: In dalex there is `TreeExplainer(explainer.model, explainer.data.values)`, and indeed `shap.TreeExplainer(catboost, X_test)` returns the above error for me. 
BTW. I see more issues like this: https://github.com/slundberg/shap/issues?q=is%3Aissue+is%3Aopen+AttributeError%3A+%27TreeEnsemble%27+object+has+no+attribute+%27values%27

I can add a workaround: 
```python
try:
   TreeExplainer(explainer.model, explainer.data.values) 
except:
    TreeExplainer(explainer.model)
```

**Comment by pa-blan** [comment]
SHAP itself is simply very poorly maintained. Not even the examples work...

**Comment by hbaniecki** [comment]
Thanks for all the issues and feedback! This example will work in the next version.
