### ISSUE TITLE
Python 3.9 / Jupyter Lab does not find "dalex" module

### ISSUE THREAD

**Issue by cramshorn-mb** [ModelOriented/DALEX#375]
Trying the Titanic example from "Explanatory Model Analysis" (great book!)  
Tried solutions for missing modules provided on StackExchange.  
Adding this issue here as you just released dalex 1.0. Please let me know if this is not the right place to raise the issue.

Error msg:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-bbe9e532a8e4> in <module>
----> 1 import dalex as dx
      2 titanic = dx.datasets.load_titanic()
      3 X = titanic.drop(columns='survived')
      4 y = titanic.survived

ModuleNotFoundError: No module named 'dalex'
```
pip3 list output:
```
Package               Version
--------------------- ---------
[...]
cycler                0.10.0
dalex                 1.0.0
decorator             4.4.2
[...]
```

**Comment by hbaniecki** [comment]
Thanks, will install Python 3.9 and see if this is an issue.

**Comment by cramshorn-mb** [comment]
I did try installing from the conosle, no difference. Tried running directly in Python, no difference. Tried with and without pip3 -U option, tried pip3 install dalex==1.0.0 - all made no difference.

**Comment by hbaniecki** [comment]
I installed Python 3.9 with new `pip` and `dalex`. `import dalex` works normally; thus, I can't really suggest a fix for now.

**Comment by cramshorn-mb** [comment]
Ok, thank you for checking.

**Comment by hbaniecki** [comment]
@cramshorn-mb you might have two python interpreters installed - one works for python/conda, and the other one is connected with pip.  See `pip3 -V`, `python -V`, `pip -V`.
Anyway, thanks for raising this issue - please, comment if this gets resolved for you.

**Comment by cramshorn-mb** [comment]
Thanks for the tips, you were right. I had installed Python 3.9 and added dalex there. My Python environments were still using Python 3.7. I have adjusted them and dalex is found now.
