### ISSUE TITLE
Support for LDA

### ISSUE THREAD

**Issue by kadyb** [ModelOriented/DALEX#378]
I tried to explain the LDA model from `MASS` package but without success. Does `DALEX` support this classifier?

```r
library("mlr3")
library("MASS")
library("DALEX")
library("DALEXtra")
library("mlr3learners")

# MASS
lda_mdl = lda(iris[, 1:4], grouping = iris$Species)
explainer = explain(lda_mdl, iris[, 1:4], y = as.integer(iris$Species), type = "classification")

model_performance(explainer)
#> Error in yhat.default(explainer$model, explainer$data, ...) : 
#>   'list' object cannot be coerced to type 'double'

# mlr3
task_iris = TaskClassif$new(id = "iris", backend = iris, target = "Species")
learner = lrn("classif.lda")
learner$train(task_iris)

explainer = explain_mlr3(learner, iris[, 1:4], y = as.integer(iris$Species))

model_performance(explainer)
#> Error in if (ncol(response) == 2) { : argument is of length zero
```

> Preparation of a new explainer is initiated
>   -> model label       :  lda  (  default  )
>   -> data              :  150  rows  4  cols 
>   -> target variable   :  150  values 
>   -> predict function  :  yhat.default will be used (  default  )
>   -> predicted values  :  the predict_function returns an error when executed (  WARNING  ) 
>   -> model_info        :  package Model of class: lda package unrecognized , ver. Unknown , task regression (  default  ) 
>   -> model_info        :  type set to  classification 
>   -> residual function :  difference between y and yhat (  default  )
>   -> residuals         :  the residual_function returns an error when executed (  WARNING  ) 
>   A new explainer has been created!  

> Preparation of a new explainer is initiated
>   -> model label       :  R6  (  default  )
>   -> data              :  150  rows  4  cols 
>   -> target variable   :  150  values 
>   -> predict function  :  yhat.LearnerClassif  will be used (  default  )
>   -> predicted values  :  the predict_function returns an error when executed (  WARNING  ) 
>   -> model_info        :  package mlr3 , ver. 0.9.0 , task classification (  default  ) 
>   -> residual function :  difference between y and yhat (  default  )
>   -> residuals         :  the residual_function returns an error when executed (  WARNING  ) 
>   A new explainer has been created!

**Comment by kadyb** [comment]
This works for base `MASS` package.

```r
custom_predict = function(mdl, newdata) {
  preds = predict(mdl, newdata)$class
  preds = as.integer(preds)
}

lda_mdl = lda(iris[, 1:4], grouping = iris$Species)
explainer = explain(lda_mdl, iris[, 1:4], y = as.integer(iris$Species),
                    type = "classification", predict_function = custom_predict)
```

**Comment by maksymiuks** [comment]
Hi!

Thank you for that issue. 

DALEX and DALEXtra out of the box support only probability output type. It means that whenever you are interested only in classes you have to pass the custom predict function. Additionally, whenever you aiming for multilabel classification, the `y` parameter should have exactly the same factor levels as the `y` vector used to fit the model because it how DALEX access proper column. Below code will work perfectly fine

```
library("mlr3")
library("MASS")
library("DALEX")
library("DALEXtra")
library("mlr3learners")

# mlr3
task_iris = TaskClassif$new(id = "iris", backend = iris, target = "Species")
learner = lrn("classif.lda", predict_type = "prob")
learner$train(task_iris)

explainer = explain_mlr3(learner, iris[, 1:4], y = iris$Species)
> (model_performance(explainer))
Measures for:  multiclass
micro_F1   : 0.98 
macro_F1   : 0.9800293 
w_macro_F1 : 0.9800293 
accuracy   : 0.98 
w_macro_auc: 0.9992

Residuals:
          0%          10%          20%          30%          40%          50%          60%          70%          80%          90% 
0.000000e+00 0.000000e+00 0.000000e+00 6.883383e-16 7.991620e-07 3.537273e-06 7.800228e-05 4.486154e-04 1.803456e-03 2.106184e-02 
        100% 
8.566081e-01 
```

Plain models from MASS are indeed not supported by DALEX at the moment.

**Comment by kadyb** [comment]
Thanks for the answer. I thought `explain_mlr3` was integrated to provide reponses from `mlr3` classifiers. If you add out of the box support in the future, that will be great.
