### ISSUE TITLE
missing values in object error with randomForest

### ISSUE THREAD

**Issue by nhkhoi** [ModelOriented/DALEX#379]
In section 4.2.2 Random forest model, the code `titanic_rf <- randomForest(survived ~ class + gender + age + 
                sibsp + parch + fare + embarked, data = titanic)` generates the error `Error in na.fail.default(list(survived = c(1L, 1L, 1L, 2L, 2L, 2L, 1L,  : 
  missing values in object`. I suspect this error is cause by the fact that there is no missing data imputation for the titanic dataset.

**Comment by hbaniecki** [comment]
+ table in `4.1` doesn't show `country`

**Comment by pbiecek** [comment]
Thank you,
please note that the preprocessing (including imputations) is described in 4.1.1 http://ema.drwhy.ai/dataSetsIntro.html#exploration-titanic

the titanic dataset after imputations can be accessed via `archivist:: aread("pbiecek/models/27e5c")` or via `DALEX::titanic_imputed`

**Comment by hbaniecki** [comment]
@pbiecek `DALEX::titanic_imputed` has the target column as integers, which is why it won't work [with EMA code for model fitting](http://ema.drwhy.ai/dataSetsIntro.html#models-for-rms-titanic-snippets-for-r).

**Comment by pbiecek** [comment]
@hbaniecki the EMA examples are prepared for 
```
titanic <- archivist::aread("pbiecek/models/27e5c")
```

@maksymiuks do you remember why `titanic_imputed` has  numerical `survived` collumn?

**Comment by hbaniecki** [comment]
I am aware of that, but the above information could be misleading/wrong. 

`titanic_imputed` has a numerical `survived` column because `DALEX` operates on numerical target columns.

For me, his issue can be closed.
