### ISSUE TITLE
SSL error while acquiring model via Archivist

### ISSUE THREAD

**Issue by nhkhoi91** [ModelOriented/DALEX#380]
I use `archivist::aread("pbiecek/models/58b24")` to acquire titanic_lmr model, as guided in section 4.2.7. The generated error is `Error in function (type, msg, asError = TRUE)  : 
  error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version`.

**Comment by pbiecek** [comment]
Please share your `devtools::session_info()` or `sessionInfo()`

**Comment by nhkhoi91** [comment]
Here's the output of sessionInfo:
`R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3 tools_4.0.3  `

**Comment by pbiecek** [comment]
Thanks, it looks like it is related to lack of TLS support in git on Windows ref: https://github.com/glennhickey/progressiveCactus/issues/93 

We are working on this

**Comment by pbiecek** [comment]
@nhkhoi91 it should work with the latest version of archvist (from GitHub)
```
devtools::install_github("pbiecek/archivist")
```

**Comment by nhkhoi91** [comment]
@pbiecek thanks! It works now
