### ISSUE TITLE
plot shows nothing in ipython notebook except blank space 

### ISSUE THREAD

**Issue by JasonAn** [ModelOriented/DALEX#381]
I tried to use dalex built-in plot function (see example below) but got nothing except a blank space.

## Some technical notes:
- cell 8: train a random forest model on titanic dataset following the instruction in tutorial [tutorial](https://ema.drwhy.ai/shapley.html#SHAPPythonCode)
- cell 9: make a trivial matplotlib plot to verify the matplotlib env works well in notebook 
- cell 10: try to plot shap value for instance following the instruction in tutorial.

<img width="894" alt="dalex" src="https://user-images.githubusercontent.com/4537312/106817018-2082c500-662b-11eb-8af3-5ba0ed5dbde3.png">

**Comment by hbaniecki** [comment]
Thanks for raising this issue, it looks like some generic bug with `plotly`. Could you provide the following:
1. browser/IDE that you are using
2. Python version
3. OS
4. versions of packages by running the following script:
```python
import dalex
import pandas
import numpy
import plotly
import notebook
import IPython

# session info
pkg_dict = {}
for pkg in [dalex, pandas, numpy, plotly, notebook, IPython]:
    pkg_dict[str.split(str(pkg))[1].replace("'", "")] = pkg.__version__
pandas.DataFrame(pkg_dict, index=["version"])
```

**Comment by JasonAn** [comment]
Thanks! now it works @hbaniecki 
It turns to be the plotly configuration issue. i need to go through the trouble shooting "JupyterLab Problems" below to fix this issue.

https://plotly.com/python/troubleshooting/#jupyterlab-problems
