### ISSUE TITLE
Feature names issue

### ISSUE THREAD

**Issue by naimmahi** [ModelOriented/DALEX#387]
Hi,

I am recently facing this problem with the feature names in DALEX. If feature names contain "-", it shows warning in the predict function. I tried with several datasets and getting the same warning/error. Below is a screenshot of the error. For example, feature H1-2 is in the list. I tried with caret predict function and works fine. Any help would be much appreciated.

Thanks,
Naim

![Capture](https://user-images.githubusercontent.com/18692309/108535410-ed823780-72a0-11eb-8b6d-9e95af46acdd.PNG)

**Comment by pbiecek** [comment]
Thanks,
@naimmahi would you share an example that can be reproduced?
@maksymiuks @hbaniecki any idea what causes this?

**Comment by hbaniecki** [comment]
This error occurs when there is no such column in the dataset. We shall see the predict function.

**Comment by hbaniecki** [comment]
Closing due to a month without response.
