### ISSUE TITLE
Regression models support in fairness

### ISSUE THREAD

**Issue by jakwisn** [ModelOriented/DALEX#391]
It would be awesome to have support for regression models in `dalex.fairness` module. It should have some of the features pointed below: 
* Density plot - showing the density of prediction for each subgroup
* PDP-like plot - for each subgroup
* Metrics that would allow for a plot like `fairness_check` 
* Assuming that the fairness for regression models won't be as rich as for classification, there should be a way to transform the regression model/explainer into a classification model

**Comment by hbaniecki** [comment]
Let's actually introduce measures for regression models in a more 'paper/research' format (or find existing solutions).
