### ISSUE TITLE
Constraints in the features contribution calculation?

### ISSUE THREAD

**Issue by PaoloCordella** [ModelOriented/DALEX#40]
Hi,

Is there a way to enforce constraints in the features contribution calculation resulting from prediction_breakdown , for example to enforce some features to have positive contribution?

Please note I'm already using monotonicity constraints in the xgboost training.

Thanks

**Comment by pbiecek** [comment]
Not yet. I'm not sure if it's possible in a model agnostic way. 
But it would be an interesting feature. 
Added to TODO

**Comment by mstaniak** [comment]
Curious: where would a priori knowledge about the sign of the contribution come from?

**Comment by pbiecek** [comment]
@mstaniak Like in the FICO challenge. One is modelling the probability of default and there is a feature: external risk score. One can assume positive monotonic relation between external score and the new score.

**Comment by pbiecek** [comment]
close due to lack of human resources
