### ISSUE TITLE
Python explainer's type="break_down" bug

### ISSUE THREAD

**Issue by Kostee** [ModelOriented/DALEX#401]
I tried pretty simple explainer on SVC binary classification for Red Wine Quality dataset and it failed on creating the table created by *predict_parts()* method. As a result, an incorrect visualization also was generated. There's something wrong with the "alcohol" column - it should appear at the top, not at the bottom, which also breaks the plot.

Dataset link: https://www.kaggle.com/uciml/red-wine-quality-cortez-et-al-2009
(.csv in the same source as script)

```python
#load packages
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
import dalex as dx

#prepare dataset
df = pd.read_csv("winequality-red.csv")
df["quality"] = df["quality"].apply(lambda x: 1 if x > 5 else 0)

#model
X_train, X_test, y_train, y_test = train_test_split(df.drop("quality", axis=1), df["quality"], test_size = 0.25, random_state = 1613)
svc = SVC(kernel = 'linear')
svc.fit(X_train, y_train)

#explainer
explainer = dx.Explainer(svc, X_train, y_train)
pp = explainer.predict_parts(X_train.iloc[31,:], type = "break_down") # generates incorrect result
pp # looks like below:
```
![image](https://user-images.githubusercontent.com/38791658/112683962-ac1e1280-8e72-11eb-89ce-22e44b3f821c.png)
```python
pp.plot() # also not correct
```
![image](https://user-images.githubusercontent.com/38791658/112684021-be984c00-8e72-11eb-8c93-94b946fbde99.png)

Everything worked properly with standard explainer method and shapley values.

**Comment by hbaniecki** [comment]
Thanks,
the result seems fine. This particular instance has `alcohol` equal to the mean of the training dataset. `type='shap'` shows it as non-important (hence probably the order of variables here), while `type='break_down_interaction'` indeed finds interactions with `alcohol`. There was a bug in `plot` function when `max_vars <= n_variables` which makes the last bar invisible.
Attaching a notebook to document the fix [wine_bd.zip](https://github.com/ModelOriented/DALEX/files/6214279/wine_bd.zip).
