### ISSUE TITLE
Error in multiclass explainer on model with one variable

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/DALEX#405]
related to: ModelOriented/modelStudio#99
```r
library(DALEX)
library(ranger)
temp <- subset(HR, select = c("status", "age"))
model_ranger <- ranger(status ~., temp, probability = TRUE)
explainer_ranger <- explain(model_ranger,
                           data = temp[, 2, drop=FALSE],
                           y = temp$status)
```

**Comment by pbiecek** [comment]
what is the expected behaviour here?
`head(predict(explainer_ranger, temp))` is working fine

@maksymiuks shall the `explain()` function detect the multilabel classification? the warning is not needed

**Comment by hbaniecki** [comment]
`explain()` didn't detect the multilabel classification because of `data[1:2,]` usage (predict returned an error). I fixed this already.

**Comment by pbiecek** [comment]
@hbaniecki what does it mean `data[1:2,]` usage ?

**Comment by hbaniecki** [comment]
`data[1:2,]` was used in `explain()` code:

![image](https://user-images.githubusercontent.com/32574004/113479288-82767400-948e-11eb-82c0-206b29aba37c.png)

Details: https://github.com/ModelOriented/DALEX/commit/d2a1e4958595d954ce560f7066d95558a050ecdb

**Comment by pbiecek** [comment]
Is there a need for changing a name of a function `check_if_multiclass`? 
This creates a risk for lack of backward compatibility

Please set reviewer before merging with master

Do we need two rows there? 
This may not work with data that contains only a single row.

**Comment by hbaniecki** [comment]
There is no risk since this is an internal function used only in `explain()`. As for the rows, @maksymiuks could know better (I only fixed the bug).

**Comment by pbiecek** [comment]
it can be used by some other package than `DALEX`
@maksymiuks do we need two rows here?
