### ISSUE TITLE
Multiprocess error

### ISSUE THREAD

**Issue by gsndr** [ModelOriented/DALEX#414]
When I use processes =2 in model_parts the code returns this error:
File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle weakref objects

What is the problem?

**Comment by hbaniecki** [comment]
Good question, I see numerous similar (unresolved) issues [on stackoverflow](https://www.google.com/search?q=TypeError:+can%27t+pickle+weakref+objects+site:stackoverflow.com). I see Python 3.6. What is your `dalex` version?

**Comment by gsndr** [comment]
I have an old version of Python 2.7 and the version of Dalex is 1.1.0

**Comment by gsndr** [comment]
The version of Dalex is 1.1.0

**Comment by hbaniecki** [comment]
Looking at `File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps` I believe that you use Python 3.6. Nevertheless, `dalex` supports `python>=3.6`.

Are you using `processes=2` with the `keras` models? These have problems with `pickle` (hence also multiprocessing in Python) for a long time now (see https://github.com/ModelOriented/DALEX/issues/256, https://github.com/tensorflow/tensorflow/issues/34697#issuecomment-627193883, https://github.com/tensorflow/tensorflow/pull/39609/).

**Comment by gsndr** [comment]
Hi, thanks for the answer. I tried to run the code also with Python 3.8 but the error is the same. 
I'm using a keras model. Maybe the problem is  the compatibility with Keras model

**Comment by gsndr** [comment]
I solved by changing in dalex/model_explanations/_variable_importance/utils.py
the row 22 from:
 ` pool = mp.Pool(processes)`
to 
` pool = mp.pool.ThreadPool(processes)`
Now the multiprocess works.
