### ISSUE TITLE
Train data or test data should be used in explain method?

### ISSUE THREAD

**Issue by neuideas** [ModelOriented/DALEX#423]
Hi everyone
'
In some of the tutorial about Dalex, train data is used in explain().. My question and confusion is if we have perform the instance-level explanations, ideally it should be with test data and for that, we should know in advance which instances are of test data? Am I wrong?

Similarly, which data (train or test) should be used in explain () if we are using dataset-level feature importance?

Kind regards

**Comment by pbiecek** [comment]
This is a very good question, we are just finishing an article on this topic. 
It should be ready this week, we will link it here.

**Comment by neuideas** [comment]
Thank you for that. I will be waiting for the article.

Kind regards

**Comment by neuideas** [comment]
Dear sir, I am still waiting for your article to be linked here. I believe
it will help reduce the confusion about what type of data should be used
for the datasets-level and what should be considered for the instance-level
explanations.

Kind regards

**Comment by hbaniecki** [comment]
Hi @neuideas, the preprint on explanation context is available at https://arxiv.org/abs/2105.13787.

Concerning your original question: I believe that in the world of model-specific feature importance methods we observe both approaches. The split criterion measure in decision trees connects to the training dataset, while the permutational importance in random forests is usually calculated on the Out-of-bag data - one could think of it as a "validation" approach. Nevertheless, it might be useful to compare dataset-level explanations on the training dataset (we aim to understand the patterns learnt by the model) with the ones calculated on the test dataset - to observe its generalization capabilities.

**Comment by pbiecek** [comment]
As Hubert wrote, the preprint is available on arxiv from today.
To the question of which dataset to choose the short answer: it depends.
As we show in the paper, for some issues depending on the question posed it is better to choose a different dataset.

**Comment by neuideas** [comment]
Thank you for the nice work. I will read the paper and will come back if
found some confusion.

Best regards
