### ISSUE TITLE
DALEX::plot.model_performance() rejects list of model_performance objects

### ISSUE THREAD

**Issue by agilebean** [ModelOriented/DALEX#424]
The `DALEX::plot.model_performance()` has an extremely useful option that plots several model_performance objects as described in the book [Explanatory Model Analysis](https://ema.drwhy.ai/residualDiagnostic.html#RcodeResidualDiagnostic):

`plot(mr_lm, mr_rf, geom = "histogram")`

This is extremely useful.

```
plot(xai.list.DALEX$gbm$performance.DALEX,
     xai.list.DALEX$rf$performance.DALEX,
     geom = "histogram")
```
shows
![image](https://user-images.githubusercontent.com/28497542/120915211-89fc0880-c6dd-11eb-8239-29d9dcd93db2.png)

However, the plot function rejects a list of model objects:
```
xai.list.DALEX %>%
  map("performance.DALEX") %>% 
  plot(geom = "histogram")
```

The documentation for `DALEX::plot.model_performance` says about the input:
`x a model to be explained`

### Big question:
Is it somehow possible to input a list of model_performance objects to plot()?
Either by extending `DALEX::plot.model_performance`, or by transforming the list of model_performance objects somehow?

As the model_performance objects are mostly assembled in a list,
would be very useful for lots of use cases!

**Comment by pbiecek** [comment]
@agilebean please try https://github.com/ModelOriented/DALEX/commit/6751ac9fb8d19bca7b8026f8aa2d0abf0cd4ace4
now the `plot` function should work for lists (not only performance explanations but all other explanations as well).

**Comment by agilebean** [comment]
@pbiecek thanks so much for the commit so fast.

I tried it out now but unfortunately get this error:

```
Error in plot.model_performance(lm = list(residuals = list(predicted = c(1939.5536628618,  : 
  argument "x" is missing, with no default
```

However, I finally create a reprex:

```
libs <- c("DALEX", "tidyverse", "caret")
SEED <- 171

dataset <- diamonds %>%
  select(is.numeric) %>%
  sample_n(1000)

target <- dataset$price
features <- dataset %>% select(-price)

algorithm.labels <- c("lm", "knn", "gbm", "rf")

plan(multicore, workers = 8)

mlist <- algorithm.labels %>%
  future_map(
    ~ caret::train(
      method = .x,
      x = features,
      y = target,
      preProcess = c("center", "scale"),
      trControl = trainControl(method = "cv", number = 5)
    )
  ) %>%
  set_names(algorithm.labels)

xai.list <- mlist %>%
  future_map(
    ~.x %>%
      DALEX::explain(
      data = features,
      y = .x$trainingData$.outcome >= (target %>% quantile(.95)),
      label = paste(.x$method, " model"),
      colorize = TRUE
    ) %>%
      DALEX::model_performance(),
    .options = furrr_options(seed = SEED)
  )

xai.list %>% plot()
```
If `plan(multicore)` doesn't work for you, just replace it by `plan(multisession)`.
Or just use `map` instead of `future_map` if you can wait.

**Comment by pbiecek** [comment]
Thank you,
it turns out that list with arguments should not be named,
I've just commited a hotfix, it works for the example above

Let me know if there are any issues with this fix

**Comment by agilebean** [comment]
@pbiecek thanks, i tested the hotfix.

`xai.list %>% plot()`
now shows the cumulative distribution of residuals - very nice:
![image](https://user-images.githubusercontent.com/28497542/121283440-11cc5780-c916-11eb-9e19-dde9158334ea.png)

However,
`xai.list %>% plot(geom = "histogram")`
or
`xai.list %>% plot(geom = "boxplot")`
throws
`Error: $ operator is invalid for atomic vectors`

**Comment by pbiecek** [comment]
sorry for this, 
some names needs to be kept
this one: https://github.com/ModelOriented/DALEX/commit/95b604008ecda6336a2b1f40bc0629a8c37a3882
is working for both scenatios

**Comment by agilebean** [comment]
@pbiecek 
great!, it works like a charm now!

`xai.list.DALEX  %>% plot(geom = "histogram")`
plots
![image](https://user-images.githubusercontent.com/28497542/121524554-636a0480-ca32-11eb-814f-466c12fc718e.png)

really nice work!
