### ISSUE TITLE
model_parts() does not read default for argument loss_function

### ISSUE THREAD

**Issue by agilebean** [ModelOriented/DALEX#425]
In the documentation of `model_parts()`, the argument loss_function is defined:

```
model_parts(
  explainer,
  loss_function = loss_default(explainer$model_info$type),
  ...
)
```

and the behavior of the default for argument `loss_function ` is explained as:

loss_function a function that will be used to assess variable importance. By default it is 1-AUC for classification, cross entropy for multilabel classification and RMSE for regression.

However, calling model_parts without loss_function (assuming `loss_default` is called) 

```
        DALEX.explainer %>%
          model_parts(
            explainer = DALEX.explainer,
            B = no_permutations,
            type = "ratio"
          )
```

throws error:

```
Error in loss_function(observed, predict_function(x, sampled_data)) : 
  could not find function "loss_function"
```

What is wrong here?
maybe loss_default does not access the explainer correctly?

**Comment by agilebean** [comment]
I think I figured it out although I don't understand the reason.

Two solutions:
a) Removing `DALEX.explainer %>% ` 

          model_parts(
            explainer = DALEX.explainer,
            B = no_permutations,
            type = "ratio"
          )

b) Removing the first argument 

        DALEX.explainer %>%
          model_parts(
            B = no_permutations,
            type = "ratio"
          )

**Comment by hbaniecki** [comment]
shouldn't `%>%` work like in B? It passes the object as the first argument

**Comment by agilebean** [comment]
> shouldn't `%>%` work like in B? It passes the object as the first argument
> 
> I believe there is no point in using `%>%` in
> 
> ```r
> DALEX.explainer %>%
>           model_parts(
>             explainer = DALEX.explainer,
>             B = no_permutations,
>             type = "ratio"
>           )
> ```

I got that, but the question is why exactly?
The pipe tries to insert the first argument, which is already assigned.
So what happens next in the R compiler??

**Comment by hbaniecki** [comment]
I believe that is a question to the developer of `%>%` and `R`; not so much an issue of `DALEX`

**Comment by agilebean** [comment]
fair enough ;-)
