### ISSUE TITLE
iBreakDown::local_attributions() throws Error: "undefined columns selected"

### ISSUE THREAD

**Issue by agilebean** [ModelOriented/DALEX#426]
I trained 5 models with caret::train.
The following code works for svmRadial, gbm and rf, BUT NOT for lm, knn:

```
DALEX.explainer <- model %>%
  DALEX::explain(
    data = features,
    y = model$trainingData$.outcome >= UPPER.MIN,
    label = paste(model$method, " model"),
    colorize = TRUE
  )

DALEX.attribution <- DALEX.explainer %>%
  iBreakDown::local_attributions(
    local.obs,
    keep_distributions = TRUE
  )
```
throws error:

```
Error in `[.data.frame`(newdata, , object$method$center, drop = FALSE) : 
  undefined columns selected
```
In the documentation, I couldn't find any hint that the function is model-dependent.
Any clue why this doesn't work for lm and knn??

**Comment by agilebean** [comment]
local.obs is a random sample from the caret::train object `model`,
i.e. `model$trainingData %>% sample_n(5)`

**Comment by hbaniecki** [comment]
`iBreakDown::local_attributions` takes only `1` observation as an input

**Comment by agilebean** [comment]
Hm but why does the exactly the same code work for gbm, rf, and svmRadial?

**Comment by hbaniecki** [comment]
It would be easier to help with a reproducible example (code+toy dataset). I can only guess that you could compare `colnames(features)` and `colnames(local.obs %>% sample_n(1)`

**Comment by agilebean** [comment]
i will try to make a reprex later.
to answer to your guess, yes the differences is the target column of the caret::train object `.outcome`
I got it from the documentation for

`new_observation | a new observation with columns that correspond to variables used in the model.`

new_observation includes the target, or does it expect only the features?

**Comment by hbaniecki** [comment]
It's preferable to input only the features, but supplying `new_observation` with the target should work. Unless it has a different column name as in this example

**Comment by agilebean** [comment]
Finally I figured it out, it was very tricky and just a special case but worthwhile sharing.
Three conditions define this case:

1. The problem is created when the `DALEX::explain()` is fed with the features derived from the caret::train object (here called `model`).
2. Some features are categorical. For lm and knn, these features must be one-hot encoded. As a result, the `model$trainingData` contains the new one-hot encoded numeric features. 
3. If any DALEX function is fed with the original features (e.g. passed as argument), then it throws the error "undefined columns selected" because these differ from the one-hot encoded new features.

So the solution is either to pass the original features to DALEX::explainer and new observation built from these,
or retrieve the features from the `caret::train` model object, and build new observations from `model$trainingData`

**Comment by hbaniecki** [comment]
I believe that a nice solution to variable transformations is to treat the model as a Pipeline like in `scikit-learn` or `mlr3`. Then, you pass the original data into both: the model and `explain`, while the pipeline transforms the features (it can be any custom function that first transforms the data, and then makes the prediction).

**Comment by agilebean** [comment]
@hbaniecki
Your comment makes me finally understand why the `recipes` package is important. That does exactly what you describe, the feature preprocessing pipeline. 
Thanks for the inspiration!
