### ISSUE TITLE
Error message in explainer

### ISSUE THREAD

**Issue by Nehagupta90** [ModelOriented/DALEX#427]
I run an explainer on binary data (output variable has Yes/No values). When I train & train the model, it works fine. The explainer is also created successfully but when I use the explainer on a single observation i..e instance-level explanation, it gives me the following error message:

Error in if (ncol(response) == 2) { : argument is of length zero

The code I used is here:

data=readARFF("aho.arff")

task=TaskClassif$new("data", backend=data, target = "isKilled")

learner= lrn("classif.randomForest")

learner1=learner$train(task)

p= learner1$predict(task)

explainer= explain_mlr3(learner1, data=data[,-15], y= data$isKilled, label="RF")

module= data[11,]
plot(predict_parts(explainer,module, type= "break_down_interactions")) /// error is here in the last step

**Comment by hbaniecki** [comment]
For binary classification, `y` must be a numeric vector `0/1`, which should be also indicated in the `explain_mlr()` verbose output.

**Comment by Nehagupta90** [comment]
So I should convert values Yes and No to 0 and 1?

**Comment by hbaniecki** [comment]
Exactly, as these will be compared to the probabilities of class `1` in the explanations (predictions, residuals).

**Comment by Nehagupta90** [comment]
Thank you Hubert for the clarification.

Warm regards

**Comment by hbaniecki** [comment]
Regards
