### ISSUE TITLE
Statistical tests in XAI

### ISSUE THREAD

**Issue by Nehagupta90** [ModelOriented/DALEX#429]
Hello everyone

I wonder if there is any statistical tests in XAI where we compare that one group of data is significantly better than the other. I read somewhere about factor merger but could not understand.. Moreover, I think it is not for continous and regression-based data.. 
Thanks

**Comment by leonardoarjs** [comment]
Hello there. What do you mean by "significantly better" ?

**Comment by Nehagupta90** [comment]
I mean if there is a significance difference (mean or median) between the
two groups. I mean something alternative to p values and effect size tests.

**Comment by hbaniecki** [comment]
@Nehagupta90 could you be more specific? 
> significance difference (mean or median) between the two groups

Do you mean differences in the model's predictions or reasoning?

**Comment by Nehagupta90** [comment]
Yes... For instance, we have two groups of data

A= c(3.4, 5.0, 5.5, 1.2)
B= c (1.2, 1.5, 3.4, 2.5)

There is a significant difference between the two groups because p < 0.05..

Something like that..  Alternative to wilcoxon test, t-test etc

**Comment by hbaniecki** [comment]
@Nehagupta90 but where is the model in question?

**Comment by Nehagupta90** [comment]
It could be any model. I mean if we have some output from a nnet model and
another output from svm model and we need something like

Wilcox.test(nnet, svm)

The above test will give us output (in form of p values) that there is a
significant difference between the two algorithms. My question is can we
produce this type of analysis (significant difference) via xai? I think
factor merger is one library in dalex but I guess it only works with
categorical variables.

Thank you

**Comment by hbaniecki** [comment]
I guess there are no such tests in DALEX
