### ISSUE TITLE
How to interpret an instance-level explanation

### ISSUE THREAD

**Issue by Nehagupta90** [ModelOriented/DALEX#430]
Hi I have a bit confusion over a plot of instance-level explanation.. I have to predict something which has a value of 0 to 10, while 10 means a product is very expensive and 0 means it is not expensive at all. I get a prediction of 0.7 (which of course means not expensive) and majority of input features have negative impact (red bars instead of green bar). So my question is how to interpret this explanation. If the value of this input feature will decreases, the prediction will decrease (go from 0.7 to 0.0) or the prediction will increase (goes from 0.7 to higher values such as 10).

Thank you and hope you have understood my point

**Comment by hbaniecki** [comment]
Hi @Nehagupta90,
It would be best to start by taking a look at an _Explanatory Model Analysis_ book at https://ema.drwhy.ai/, which explains these topics in detail, e.g. instance-level explanation https://ema.drwhy.ai/InstanceLevelExploration.

**Comment by Nehagupta90** [comment]
Hello and thanks..

I have read this book to some extent and will read it again.. But kindly if
you could answer it briefly and if I re-read the book after your
explanation, I believe I will understand the point even more better.

Warm regards

**Comment by hbaniecki** [comment]
Sure, could you attach your figure, so I can comment on that?

**Comment by Nehagupta90** [comment]
Thank you.. I dont have in hand the example I mentioned earlier but will
provide another similar example..

I provide another example here where I predict bugs in a software system.
Values are from 0-5 with 0 means no bugs and 5 means 5 bugs.

I pasted here the figure as well as attached the file (dont know which one
will work here)

[image: image.png]

**Comment by hbaniecki** [comment]
It didn't attach by email

**Comment by Nehagupta90** [comment]
![image](https://user-images.githubusercontent.com/58039529/123270913-9b784980-d500-11eb-9411-956c975a6217.png)
![Untitled2](https://user-images.githubusercontent.com/58039529/123270958-a4691b00-d500-11eb-8595-8c033e133cbd.png)

**Comment by Nehagupta90** [comment]
sorry pasted twice

**Comment by hbaniecki** [comment]
`intercept` is a baseline prediction, specifically the mean of the model's predictions on the supplied dataset. 

For a given instance, the model predicted a value of `0.069` (lower than the baseline), and several variables contribute negatively to this outcome (`loc`, `rfc`, `lcom`, `max_cc`, `ce`, an INTERACTION of `ca` and `cbo` etc.), while others contribute positively to this outcome (`noc`, `npm`). 

Note that we won't answer the "What if ..?" question using this explanation -- it can be answered by the `predict_profile()` explanation visualization for a given variable in data. I highlighted the interaction between variables `ca` and `cbo`, as well as `cbm` and `ic`, as these become more apparent in non-additive models (See https://arxiv.org/abs/1903.11420 and/or try to rise the `interaction_preference = 1` attribute in `predict_parts()`). 

Hope this helps

**Comment by pbiecek** [comment]
@Nehagupta90 try `iBreakDown::describe()` function, it will generate text description out of the explaination

**Comment by Nehagupta90** [comment]
Thanks a lot for your detailed comments. Indeed it helped.

Just a quick question here, loc feature (which has a negative impact on the
outcome ) is the line of code, which means the number of bugs (output
feature which is almost zero here) will not exist if we have a less number
line of codes? Am I wrong? Of course, number of bugs will not depend only
on the line of code feature but I just giving example of this one feature.

Warm regards

**Comment by Nehagupta90** [comment]
Ok Sir, thank you. I will check this.

How much there is a chance (based on your experience) that I will get the
same results when I use iBreakDown and then use the Shapley values. Is
there any scenario where we need to prefer one over the other.

Warm regards

**Comment by hbaniecki** [comment]
> Ok Sir, thank you. I will check this. How much there is a chance (based on your experience) that I will get the same results when I use iBreakDown and then use the Shapley values. Is there any scenario where we need to prefer one over the other. Warm regards

Shapley values explanation is an average over `B = 10/15/20/25` variable paths (orderings) of the BreakDown explanation, meaning it will compute longer and show the certainty of each variable importance (boxplot). The `iBreakDown` explanation aims to find local interaction between variables, which are apparent in ML algorithms, e.g. random forests and gbm. Rising `interaction_preference = 1` should give more preference to combining variables into pairs of interacting variables.

> Thanks a lot for your detailed comments. Indeed it helped. Just a quick question here, loc feature (which has a negative impact on the outcome ) is the line of code, which means the number of bugs (output feature which is almost zero here) will not exist if we have a less number line of codes? Am I wrong? Of course, number of bugs will not depend only on the line of code feature but I just giving example of this one feature. Warm regards

As I said, you are asking a "What if?" question here and it should be answered with the [Ceteris Paribus explanation](https://ema.drwhy.ai/ceterisParibus.html) not BreakDown.

**Comment by Nehagupta90** [comment]
Good morning and thank you the explanation. I am also providing a Ceteri
Paribus Profile for each explanation. I mean when I perform the explanation
for an instance, I note the first three impactful features and then perform
the Ceteri Paribus profile for those three features.

Thank you again.
