### ISSUE TITLE
About aggregate Ceteris Paribus Profile

### ISSUE THREAD

**Issue by Nehagupta90** [ModelOriented/DALEX#433]
Dear experts of Dalex and XAI

I used the following code to perform an instance-level explanation for 100 observations in my test data.. Then I run the CP and aggregate profile for one variable, 
which gives me the graph below at the bottom.. My questions:

 (1) Does this graph represent the average/mean of 100 observations of our test data? 
 (2) What does it mean when we mention type="conditional" and "accumulated" ?
 (3) What is the meaning of cluster profile, does it divide these 100 instances into groups/clusters and provide the average profile of k-groups? If it is the case, what is its advantage over when we are not using any clusters?

new_observation= test[10:110,]
plot(predict_parts(explainer,
                   new_observation = new_observation,
                   type = "break_down_interactions"))

cp_rf <- ceteris_paribus(explainer, new_observation)
clust_rf <- aggregate_profiles(cp_rf, variables = "loc")
plot(clust_rf)

![image](https://user-images.githubusercontent.com/58039529/123950590-23989c00-d9a4-11eb-81a3-d4614e8293e8.png)

**Comment by hbaniecki** [comment]
(1) This graph represents the mean of 100 **CP profiles** of our test data
(2) Both of these are described in detail at https://ema.drwhy.ai/accumulatedLocalProfiles.html 
(3a) Yes
(3b) Ofently, CP profiles vary between the various data subgroups. Then, aggregation by mean might not be a reasonable estimation of the whole population. See Figures 17.2 and 17.3 at https://ema.drwhy.ai/partialDependenceProfiles.html.

**Comment by Nehagupta90** [comment]
Ok thank you, so what I understand is:

The CP profiles of some observations might be very different from each
other (we can consider them outliers) and hence the mean/average of the CP
profiles might not be reliable ?

The clusters will combine similar types of groups (observations) and
provide their mean/average, right ? But what would be the criteria of
choosing the number of clusters for the observations?

Does the CP support other statistics like median, stand.deviation etc ?

Warm regards

**Comment by hbaniecki** [comment]
(1) Sure. Not even outliers but for example: illustrate a simple XOR binary classification problem where you get two very different groups of CP profiles that average into a straight line.
(2a) Right.
(2b) On the criteria, I would say that it highly depends on the data and the predictive task.
(3) Median is not implemented. I believe that some analysis of CP/PDP variance is tackled by another package of ours: `vivo` https://github.com/modelOriented/vivo

**Comment by Nehagupta90** [comment]
Thank you Hubert for yet again providing useful information. I got your
points.

Warm regards

**Comment by Nehagupta90** [comment]
I am sorry because the issue is closed and I am pasting here.

For the Cluster CP, we should use the Ceteris Paribus or Partial-dependence Profile?

I mean, at the book, model_profile is used https://ema.drwhy.ai/partialDependenceProfiles.html#PDPR

And here (https://search.r-project.org/CRAN/refmans/ingredients/html/cluster_profiles.html), they used ceteris_paribus

cp_rf <- ceteris_paribus(explain_titanic_rf, selected_passangers)
clust_rf <- cluster_profiles(cp_rf, k = 3, variables = "age")
head(clust_rf)

It is very confusing for the beginners. What should we use if we have to find the average or overall behavior of a single variable. 
Thanks

**Comment by hbaniecki** [comment]
Hi @Nehagupta90, 
I believe that both approaches do the same thing -- `DALEX::model_profile()` is an abstraction over the `ingredients` functions, which is a low-level API to model analysis (maybe more advanced). Overall, for beginners, I would follow the EMA book.

**Comment by Nehagupta90** [comment]
Thanks a lot Hubert, I am clear now.

Warm regards
Neha
