### ISSUE TITLE
Change features names for plot.predict_parts

### ISSUE THREAD

**Issue by priego6** [ModelOriented/DALEX#436]
Hi everyone,

I have performed some graphs with shap values (attached is an example). However, I tried to modify the name of the variables in the y axis, and I cannot do it. I tried in different ways, anyone reports an error, but the figure keeps with the same feature names.

I would appreciate your help.

CODE:
explainer_RANDOMFOREST <- explain(modRandomForest,
                         data = DATA_train,
                         y = DATA_train$Output)

shap_RANDOMFOREST <-
  predict_parts(explainer_RANDOMFOREST,
                new_observation = DATA_train,
                type = "shap",
                N = NULL)

plot(shap_RANDOMFOREST)

#DIFFERENT TESTS TO CHANGE THE FEATURE NAMES WITHOUT SUCCESS

plot(shap_RANDOMFOREST, ynames = c("Predictor_24" = "Predictor 24",
                                   "Predictor_43" = "Predictor 43",
                                   "Predictor_55" = "Predictor 55",
                                   "Output" = "Output"))

plot(shap_RANDOMFOREST, scale_y_discrete(labels = c("Predictor_24" = "Predictor 24",
                                   "Predictor_43" = "Predictor 43",
                                   "Predictor_55" = "Predictor 55",
                                   "Output" = "Output")))

plot(shap_RANDOMFOREST, vnames = c("Predictor_24" = "Predictor 24",
                                   "Predictor_43" = "Predictor 43",
                                   "Predictor_55" = "Predictor 55",
                                   "Output" = "Output")))
![Rplot](https://user-images.githubusercontent.com/87357938/125405417-9e53b500-e3af-11eb-9b6c-661ea9b8097b.jpeg)

**Comment by hbaniecki** [comment]
Hi @priego6,
I guess that the plot is flipped, so you need to change `x` axis labels. Here is an example:

```r
library(DALEX)

new_dragon <- data.frame(
  year_of_birth = 200,
  height = 80,
  weight = 12.5,
  scars = 0,
  number_of_lost_teeth  = 5
)
library("ranger")
model_ranger <- ranger(life_length ~ year_of_birth + height +
                         weight + scars + number_of_lost_teeth,
                       data = dragons, num.trees = 50)

explainer_ranger <- explain(model_ranger,
                            data = dragons,
                            y = dragons$year_of_birth,
                            label = "model_ranger")

shap <- predict_parts_shap(explainer_ranger, new_observation = new_dragon)

plot(shap)

library(ggplot2)

plot(shap) + scale_x_discrete(labels = letters[1:5])
```

**Comment by priego6** [comment]
Hi @hbaniecki,

Thanks for your help!!! 

I tried also with scalse_x_discrete, but looking your code I understand that the problem was that my code was:

plot(shap_RANDOMFOREST, scale_x_discrete(labels = c("Predictor_24" = "Predictor 24",
"Predictor_43" = "Predictor 43",
"Predictor_55" = "Predictor 55",
"Output" = "Output")))

And to work it needs to be:

plot(shap_RANDOMFOREST, scale_y_discrete(labels = c("Predictor 24",
"Predictor 43",
"Predictor 55",
"Output")))

Thanks!!!
