### ISSUE TITLE
SHAP values for Prophet Model with DALEX

### ISSUE THREAD

**Issue by Shafi2016** [ModelOriented/DALEX#440]
Hello @hbaniecki , I am finding shap values for the prophet model as given below. Though it works fine. However, I do not understand what type of shap DALEX applies. I have seen usually people **KernelExplainer** for models except for decision tree-based and deep learning models. 
```

explain_prophet <- DALEX::explain(model = prophet,
                               data = train_tbl, 
                               label = "Prophet Model")
 shape_values <- predict_parts(explainer = explain_prophet , 
                                new_observation = test_tbl, 
                                type = "shap")
```

**Comment by hbaniecki** [comment]
Hi @Shafi2016, the algorithm is described in detail at https://ema.drwhy.ai/shapley.html

**Comment by Shafi2016** [comment]
Thanks, @hbaniecki  Actually, I want to know what type of shap method DALEX package applies? We have different shape methods such as  "KernelExplainer", "decision tree-based", and "deep learning models. It is not obvious from DALEX which method it applies. If you can please let me know.

**Comment by hbaniecki** [comment]
It is neither one of these methods. DALEX applies a [Shapley value estimation algorithm](https://ema.drwhy.ai/shapley.html) using from the [`iBreakDown::shap`](https://modeloriented.github.io/iBreakDown/reference/break_down_uncertainty.html) function; this is averaging `B` (bootstrap) number of `break_down` paths (explanations). Efficient SHAP values for tree-based models are available in the [`treeshap`](https://github.com/ModelOriented/treeshap) package.

**Comment by Shafi2016** [comment]
Thank you so much for the clarification.
