### ISSUE TITLE
Settings of the PD Profile

### ISSUE THREAD

**Issue by Nehagupta90** [ModelOriented/DALEX#443]
Hi, I have the following PD profile.. I have some visualization problem with it as shown at the top left, where the text of an important feature (Duration) and "Created for the RF model".. How can I adjust the settings of this figure?

I currently just used a simple plot as:

plot(pdp_rf) 

![image](https://user-images.githubusercontent.com/58039529/127197933-464c1d71-c0a5-4082-af8b-f13d92ee88bc.png)

**Comment by pbiecek** [comment]
hi,
it's `ggplot2` object, 
you can modify title/subtitle by adding `+ ggtitle(title, subtitle)`
(add newline or remove subtitle)
or you can change size/margins by using `+theme()`

**Comment by neuideas** [comment]
@pbiecek thanks a lot..

**Comment by hbaniecki** [comment]
Indeed, all options can be changed with `ggplot2`
