### ISSUE TITLE
Difference between PD profile and CP profile when we manually specify the instances

### ISSUE THREAD

**Issue by Nehagupta90** [ModelOriented/DALEX#444]
Hi

If I have 100 observations/instances and want to create the PD profile of few important features, then what is the difference between the PD profile of these instances using

variab= c("var1","var2", "var3" )
pdp <- model_profile(explainer = explainer, variables = variab)
plot(pdp)

and between the CP profile when we manually specify the instances like

new_observation= data[c(2,7,8,11,15,16,21,24,25,26,30,45,46),]
cp<- ceteris_paribus(explainer, new_observation)
cp_agg <- aggregate_profiles(cp, variables =  variab)
plot(cp_agg)

**Comment by hbaniecki** [comment]
Hi, the diffrerence is that in the second case you create the PD profile based on only a subset of `data` rows (I see 13 observations), while in the first case you use `N = 100` observations to estimate the PD profile.

**Comment by Nehagupta90** [comment]
Thank you Sir

So is it a good idea to provide the profile for specific instances rather
than just one profile for all instances.. Let me explain:

I predict the Results of students of 100.. Some students/instances are good
students/instances, some average and some novice. Now is it a good idea to
provide the profile of instances predicted as **good**, another profile for
**novice** students and so on? Do you think it is a good idea or just
providing the PD profile which averages all the instances?

Warm regards

**Comment by hbaniecki** [comment]
It depends on the explanation that you want to achieve. In `model_profile` there are `groups` (group profiles/instances by a variable) and `k` (cluster profiles/instances) parameters that allow for customization. Actually, we discuss the context of creating explanations in the paper https://arxiv.org/abs/2105.13787, and specifically the context of profiles in https://arxiv.org/abs/2105.12837. Hope it helps

Kind regards

**Comment by Nehagupta90** [comment]
In model_profile there are groups (group profiles/instances by a variable)
and k (cluster profiles/instances) parameters that allow for customization

Hi Hubert, could you please the link to this group profiles? Is it allow
the same type of instances to be in one group and another type of instances
in another group?

**Comment by hbaniecki** [comment]
It is all in the documentation https://modeloriented.github.io/DALEX/reference/model_profile.html. Yes, you might want to group observations by a categorical variable.

**Comment by Nehagupta90** [comment]
It does not work with numeric variables? I have mostly numeric variables in
my dataset.

**Comment by hbaniecki** [comment]
Well, the colour is a group determined by a category. You could probably dichotomize a variable. Any specific use case can be customized/programmed, so can the groups in `aggregate_profile`

**Comment by Nehagupta90** [comment]
Thanks a lot @Hubert for the useful information.
