### ISSUE TITLE
Interpretation of the feature importance

### ISSUE THREAD

**Issue by Nehagupta90** [ModelOriented/DALEX#453]
Hello, I have the following figure for feature importance. I cannot interpret this figure properly, so kindly if you could explain the following for me?

(a) The length of the bar shows importance of a feature, but what does the last features show which are at the left side?

(b) What the boxplots inside the figure represent? 

![image](https://user-images.githubusercontent.com/58039529/129874330-238c44dd-04c6-43d2-b102-cf7aa3522a07.png)

**Comment by hbaniecki** [comment]
Hi, the intuition behind the bar value is: *How does the model's performance change when we remove an effect of any given variable?* In this case we randomly permute the column values. So bar values below the baseline [bar start, which is set at the model's performance] show that randomly permuting the variable's values would **increase** the performance (lower RMSE error). This might show off, e.g. when the model is badly fitted to the predictive task. 

The bar value is mean over `B = 10` (function parameter) bootstrap runs, while the boxplot accounts for the other statistics.  More can be read at https://ema.drwhy.ai/featureImportance.html.

**Comment by Nehagupta90** [comment]
@hbaniecki thank you.. Which is the baseline in the above figure ? The bar of the first feature (RMSE value around 3800) or bar of the last feature (RMSE value around 300) ?

**Comment by hbaniecki** [comment]
The baseline should be the dotted line in the middle (around 3900).

**Comment by Nehagupta90** [comment]
Thank you again.. So it means, more performance loss, more valuable feature? In this case, the second, third, fourth, fifth features (which have small bars but on the right side of the bar) are valuable than the last features, which are large in bar size but at the left side of the baseline?

**Comment by hbaniecki** [comment]
> So it means, more performance loss, more valuable feature?

Yes.

> In this case, the second, third, fourth, fifth features (which have small bars but on the right side of the bar) are valuable than the last features

Yes.

> which are large in bar size but at the left side of the baseline?

This might be hard to interpret at first. Why would permuting the last features improve the model? You might try to remove them and see if the model achieves a better fit/performance. 

It is also worth noting that this model-agnostic feature importance measure might not capture interactions in models/work with correlated features well.

**Comment by Nehagupta90** [comment]
It is also worth noting that this model-agnostic feature importance measure might not capture interactions in models/work with correlated features well.

Then what is the best approach in XAI for features selection? I have few features that are corelated..

**Comment by hbaniecki** [comment]
@Nehagupta90 please consider finding answers to these questions in books/resources available on the topic of feature selection (e.g. [An Introduction to Statistical Learning](https://www.statlearning.com/)).
