### ISSUE TITLE
predict_profile() returning emptiness after random frost model imputation & Error: names do not match previous names

### ISSUE THREAD

**Issue by kamaulindhardt** [ModelOriented/DALEX#467]
Dear DALEX maintainers and experts,

Thank you for this great package. It is of enormous value when trying to communicate black-box models to stakeholders. 

Lately, I have become a fan of the ```predict_profiles()``` function but have run into a problem when using it with my random forest explainer. Help would be appreciated!

```
Prediction_profiles_rf_cont <- 
DALEX::predict_profile(explainer = explainer_rf_continous, new_observation = obs_2)
```

```
Prediction_profiles_rf_cont %>% 
plot(variables = c("PrName", "Out.SubInd", "Product", "Tree", "Out.SubInd.Code","Site.Type", "Latitude", "Longitude", 
                  "Bio01_MT_Annu", "Bio02_MDR", "Bio03_Iso", "Bio04_TS", "Bio05_TWM", "Bio06_MinTCM", "Bio07_TAR", "Bio08_MT_WetQ", "Bio09_MT_DryQ", "Bio10_MT_WarQ", "Bio11_MT_ColQ",
                  "Bio12_Pecip_Annu", "Bio13_Precip_WetM", "Bio14_Precip_DryM", "Bio15_Precip_S", "Bio16_Precip_WetQ", "Bio17_Precip_DryQ", "iSDA_Depth_to_bedrock", "iSDA_SAND_conc",
                  "iSDA_CLAY_conc", "iSDA_SILT_conc", "iSDA_log_C_tot", "iSDA_FE_Bulk_dens", "iSDA_log_Ca", "iSDA_log_eCEC", "iSDA_log_Fe", "iSDA_log_K", "iSDA_log_Mg", "iSDA_log_N",
                  "iSDA_log_SOC", "iSDA_log_P", "iSDA_log_S", "iSDA_pH", "ASTER_Altitude", "ASTER_Slope", "logRR"))
```

**something weird** (this data is empty)

```
Top profiles    : 


Top observations:
```

**Errors:**

```
Warning: Unknown or uninitialised column: `_y_`, `_label_`,`_ids_`
Error in match.names(clabs, names(xi)) : 
  names do not match previous names
```

I guess its related to the additional column features generated..?

My ```explainer``` and ```obs_2``` works fine with ```predict_parts()```and ```model_profile()``` 

Thank you!

**Comment by hbaniecki** [comment]
Hi, 
can you provide a reproducible code example (e.g. with a toy dataset) where this error occurs, so we can investigate the issue?

**Comment by kamaulindhardt** [comment]
Thank you @hbaniecki ,

I found out I had to manually set up the "new" dataframe for the new observation. I thought I could simply generate it from a subset like: data[, 1] = new observation..
