### ISSUE TITLE
Wish: model_profile with individual y scale (python)

### ISSUE THREAD

**Issue by mayer79** [ModelOriented/DALEX#469]
I am using dalex for Python. It works well, thanks a lot!

Currently, plotting partial dependence profiles with `model_profile` of multiple features will use the same y-scale across all features. This is often a good idea. However, it would be nice to have an option `fixed_y=True` that could be used to override this behaviour.

This is an example with three plots with features of different magnitude of importance.

![image](https://user-images.githubusercontent.com/16206095/137584229-d9c46d23-2b01-44b2-bc5b-faf08c11161f.png)

**Comment by hbaniecki** [comment]
Thanks for the feedback Michael, will try to add such an option soon.

**Comment by hbaniecki** [comment]
added `facet_scales="free"` like for R in https://github.com/ModelOriented/DALEX/issues/468 and https://github.com/ModelOriented/ingredients/pull/140
