### ISSUE TITLE
`explain()` breaks the compliation of .Rmd to pdf with LaTeX 

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/DALEX#473]
OS: Windows 10. Compilation to HTML works fine.

Reproducible example (use in `test.rmd`):

```r
library("DALEX")
library("ranger")
library("modelStudio")

# fit a model
model <- ranger(score ~., data = happiness_train)

# create an explainer for the model    
explainer <- explain(model,
                     data = happiness_test,
                     y = happiness_test$score,
                     label = "Random Forest")
```

Outcome: 

![image](https://user-images.githubusercontent.com/32574004/141689113-f06de646-2fa3-4bc5-a0ee-9b7410a994c5.png)

**Fix**: use `verbose = FALSE`.
```r
library("DALEX")
library("ranger")
library("modelStudio")

# fit a model
model <- ranger(score ~., data = happiness_train)

# create an explainer for the model    
explainer <- explain(model,
                     data = happiness_test,
                     y = happiness_test$score,
                     label = "Random Forest",
                     verbose = FALSE)
```

We should find the symbol in verbose output that breaks this.

**Comment by piotrpiatyszek** [comment]
`1b` in hex = `33` in oct

The problem is with `escape` character, that is used to create colors  (https://en.wikipedia.org/wiki/ANSI_escape_code).
We use it there
```
color_codes <- list(yellow_start = "\033[33m", yellow_end = "\033[39m",
                    red_start = "\033[31m", red_end = "\033[39m",
                    green_start = "\033[32m", green_end = "\033[39m")
```

**Comment by pbiecek** [comment]
Colors are not rendered correctly through Rmd->html engine.
One option is to set `verbose = FALSE`
Second and less invasive is to set `colorize = FALSE` in the `explain()` function

**Comment by hbaniecki** [comment]
Potentially set `colorize = !isTRUE(getOption('knitr.in.progress'))` as a new default.

**Comment by pbiecek** [comment]
version bumped to 2.4.0 due to the chnage in defaults

**Comment by hbaniecki** [comment]
Thanks, it works well.
