### ISSUE TITLE
Lime vs iBreakdown vs Shapley methods

### ISSUE THREAD

**Issue by Nehagupta90** [ModelOriented/DALEX#474]
Hello everyone

I want to ask if the iBreakdown, Shapley methods provide the same functionality (instance level variable importance) as provide by the Lime method? I read somewhere that if we have a small-mid size features, we should use the iBreakdown, Shapley methods and if we have a huge number of features, the Lime method is preferred. 

Is this the only difference?

**Comment by hbaniecki** [comment]
Hi, answers to these questions can be found in the following books:
- [Explanatory Model Analysis](https://ema.drwhy.ai/)
- [Interpretable Machine Learning](https://christophm.github.io/interpretable-ml-book)
