### ISSUE TITLE
Can we use factorMerger to numeric data

### ISSUE THREAD

**Issue by Nehagupta90** [ModelOriented/DALEX#476]
For instance, we have two groups of data

A= c(3.4, 5.0, 5.5, 1.2)
B= c (1.2, 1.5, 3.4, 2.5)

Can we use factorMerger as:

fac= mergeFactors (response= data$A, factor= data$B, family= "guassian")

Or do we need to convert "B" to factor first?

**Comment by pbiecek** [comment]
@Nehagupta90 factorMerger combines levels in the factor variable so it will not work for numeric variable
factors are merged based on p-value for pairwise differences, but this will not work for two numeric variables
