### ISSUE TITLE
Can we use DALEX with LSTM or GRU?

### ISSUE THREAD

**Issue by Vu5e** [ModelOriented/DALEX#477]
Hello, I'm doing an experiment with DALEX and wanna run through it using LSTM on a time series dataset. But received the error in the image below. 

Is it because LSTM needs to do a 3D input shape that DALEX can't do an explainer for it?
or
Does my output of the model need to change to a pandas data frame? (The dataset is read and already set as a pandas data frame)
or
Because I fitted my data like this 

`model_GRU_RUS.fit([X_train2d_GRU_RUS, X_train3d_GRU_RUS], Y_train_GRU_RUS, epochs  = 1, batch_size = 1024, verbose = 1, validation_data = ([X_test2d_GRU_RUS, X_test3d_GRU_RUS], Y_test_GRU_RUS), callbacks=[tbCallBack])`

![dasda](https://user-images.githubusercontent.com/28688869/147779543-6e9782d5-a7ce-4b79-8dec-47029abef816.png)

**Comment by hbaniecki** [comment]
Hi, [explanations](https://ema.drwhy.ai/) in `dalex` were not designed for time-series data. I believe that 3D input is out of scope here.

It would be best to first answer the question: what explanation/visualization are you trying to obtain?

**Comment by Vu5e** [comment]
Hello hbaniecki, I wanted an explanation/visualization of how LSTM or GRU is run using Dalex. Is there any examples that Dalex can run explanation that used LSTM or GRU?

**Comment by hbaniecki** [comment]
No, LSTM and RNN are out of scope of this tool. You should probably look into specific explanations for neural networks (e.g. [Captum](https://captum.ai/) package), also for time-series data.

**Comment by Vu5e** [comment]
I managed to do it in Dalex.

First after running the LSTM model, make sure to save the model using keras model.save("example.keras"). Make sure to renamed it to ".keras".

After that for Dalex, 

`import keras.model as km

LSTM_RUS = km.load_model('LSTM_RUS.keras')
exp_LSTM_RUS = dx.Explainer(LSTM_RUS, X, Y)`

Should be able to run after that.
