### ISSUE TITLE
Plot Multiple ROC Curve for multiple explainer in one Plot?

### ISSUE THREAD

**Issue by Vu5e** [ModelOriented/DALEX#478]
Hello, I wanna ask can multiple explainers be fitted in a list and then plot multiple ROC curves out of them? I can only see an example in R. Running it in Python.

**Comment by hbaniecki** [comment]
The api is `model_performance_object1.plot([model_performance_object2, model_performance_object3])`, so I believe that something like `model_performance_list[0].plot([x for x in model_performance_list[1:])` should work.

**Comment by Vu5e** [comment]
Hello, hbaniecki. Got it. Thank you for your help. One last question, can we set the size of the figure?
![ROC Curve](https://user-images.githubusercontent.com/28688869/149880774-78b35807-e567-4af8-bfdb-607bdca8597b.png)

**Comment by hbaniecki** [comment]
@Vu5e these plots are created using the `plotly` package. Each `plot` method in `dalex` has a `show=False` parameter that returns the `plotly.Figure` object. You can customize them as appropriate, e.g. see https://plotly.com/python/setting-graph-size.
