### ISSUE TITLE
`pkgdown` deeplinking for DALEX leads to 404 for reference links

### ISSUE THREAD

**Issue by pat-s** [ModelOriented/DALEX#484]
Hi! 

(mlr3 dev here)

We see our link checker reporting some 404 on DALEX URLs (https://github.com/mlr-org/mlr3book/issues/303).

The reason is presumably caused by the deeplinking created by `pkgdown` in our bookdown-based documentation (specifically in https://mlr3book.mlr-org.com/interpretation.html).
I think `pkgdown` uses the first URL listed in the `URL` field in the `DESCRIPTION` file (which is https://dalex.drwhy.ai).

While https://dalex.drwhy.ai works, generated reference liks like https://dalex.drwhy.ai/reference/model_profile.html are 404s.

I assume (!) that this could be fixed by adding https://modeloriented.github.io/DALEX/ as the first URL into the `URL` field in the `DESCRIPTION` file as this would hopefully be picked up by pkgdown then.

**Comment by hbaniecki** [comment]
Hi @pat-s,

is it possible for you to install `DALEX` from GitHub to fix this now, or does it require a new version of the package on CRAN?

**Comment by pat-s** [comment]
AFAIK it uses the information from the local pkg installation, hence requiring DALEX dev could work ([source](https://pkgdown.r-lib.org/articles/linking.html)). 

Thanks for the quick fix, I'll give it a try right now and see if `pkgdown` picks it up right away!

**Comment by pat-s** [comment]
Worked! Thanks 🤝
