### ISSUE TITLE
Parameters of Shap or Breakdown methods

### ISSUE THREAD

**Issue by Nehagupta90** [ModelOriented/DALEX#486]
Hello group members

I am using Shap and Breakdown methods for instance-level explanations. My questions 

(1) Do these two methods provide the same functionality?

(2) Are there any parameters that we could optimize to use these two methods or we can use them as it is in the literature like below:

predict_parts(explainer, 
                   new_observation = new_observation,
                   type = "break_down_interactions")

**Comment by hbaniecki** [comment]
(1) As described in https://ema.drwhy.ai/shapley.html, Break-down visualizes an explanation of a prediction, and Shap averages `B` Break-down explanations over different orders of variables.

(2) Parameters for Break-down are listed in https://modeloriented.github.io/iBreakDown/reference/break_down.html and for Shap in https://modeloriented.github.io/iBreakDown/reference/break_down_uncertainty.html.

**Comment by Nehagupta90** [comment]
Break-down visualizes an explanation of a prediction, and Shap
averages B Break-down
explanations over different orders of variables.

Does the order of variables impact the explanation? If yes, then Break-down
would not be considered as a reliable explanation method? Am I wrong?

**Comment by hbaniecki** [comment]
Yes, the order of variables impacts the explanation. Each method has its pros and cons. It is a very broad research discourse.

**Comment by Nehagupta90** [comment]
Each method has its pros and cons.

Yes, I understand. The problem I think is we cannot measure/quantify the
explanation, so it is difficult to find which interpretation is better than
the other. Just a question in my mind: Can we gauge the quality of the
explanation tools by measuring their consistency? I mean the more
consistently LIME, Break-down and Shap produce an explanation, the better
the tool will be.

**Comment by hbaniecki** [comment]
Hi, I would recommend following the research on evaluating explanations, e.g.:
- https://arxiv.org/abs/1802.07810v5
- https://arxiv.org/abs/2101.09301
- https://arxiv.org/abs/2101.08758
- https://dl.acm.org/doi/abs/10.1145/3449213
- https://arxiv.org/abs/2106.12773
- https://doi.org/10.1145/3377325.3377519
