### ISSUE TITLE
Global feature selection using Dalex method

### ISSUE THREAD

**Issue by neuideas** [ModelOriented/DALEX#490]
Apart from Dalex model_parts and triplot, which other methods of Dalex provide feature importance at global level?

**Comment by hbaniecki** [comment]
I believe none.

**Comment by neuideas** [comment]
Hello Hubert

Are you sure there are none? I was just reading a paper (link below) about
triplot and it says there are a few like  ExplainPrediction, vimp, vip etc.
Are these not related to XAI packages?

Thank you

**Comment by hbaniecki** [comment]
Hi, you asked about methods in Dalex, and not about other packages?

**Comment by neuideas** [comment]
Ah Ok, so the ExplainPrediction is not from Dalex?
