### ISSUE TITLE
How to create an explainer on tuned models with mlr3

### ISSUE THREAD

**Issue by Nehagupta90** [ModelOriented/DALEX#496]
I have the following code, for parameters tuning with mlr3

df=readARFF("xerces.arff")
task=TaskRegr$new("df", df, target = "price") 
learner= lrn("regr.rpart")
resampling = rsmp("repeated_cv", folds=3, repeats=3)
measure= msr("regr.mae")

search_space = paradox::ParamSet$new(
 params = list(paradox::ParamDbl$new("cp", lower = 0.001, upper = 0.1)))
terminator = trm("evals", n_evals = 15)

tuner = tnr("grid_search")

at = AutoTuner$new(
  learner = learner,
  resampling = resampling,
  measure = measure,
  search_space = search_space,
  terminator = terminator,
  tuner = tuner,  store_tuning_instance = TRUE,
  store_benchmark_result = TRUE,
  store_models = TRUE 
)

bmr = benchmark(grid,store_models = TRUE)

My question is how can I create an explainer on this model? 

explainer = explain_mlr3( ??,...........)

**Comment by maksymiuks** [comment]
Hi,

Try the development version of the DALEXtra package (it should be on CRAN next week). You can get it by running `remotes::install_github("ModelOriented/DALEXtra")`.

Then simple

```
library("DAELXtra")
explainer <- explain_mlr3(at, data = df, y = df$price)
```
should work. If it does not, please provide a reproducible example so we can find a solution.

**Comment by Nehagupta90** [comment]
Thank you for your response.

Yes, I have used DALEXtra

But it gives me the following error when I use

explainer = explain_mlr3(at,
                    data = df[,-21],
                    y = as.numeric(df$price)-1 ,
                    label="DT")

Error message

Error: No task stored, and no task provided

What does it mean? Do I need to specifically split data into train and test
sets?

**Comment by maksymiuks** [comment]
Looking at the error message, it seems you are using `DALEXtra` but in a CRAN version, rather than developing one as I've suggested. Did you run `remotes::install_github("ModelOriented/DALEXtra")`?

What version is returned by `packageVersion("DALEXtra")`? It should be `‘2.1.1.9004’`.

If the version is correct but you still encounter this error, please provide a reproducible code that I could run locally (the same that ends up in an error for you) so you can track down where the issue lays.

**Comment by Nehagupta90** [comment]
packageVersion("DALEXtra")
[1] ‘2.1.1’

**Comment by maksymiuks** [comment]
Thanks for your response. Therefore installing the GitHub version of DALEXtra (`remotes::install_github("ModelOriented/DALEXtra")`) should solve your issue.

**Comment by Nehagupta90** [comment]
WARNING: Rtools is required to build R packages, but is not currently
installed.

Please download and install Rtools 4.0 from
https://cran.r-project.org/bin/windows/Rtools/.

√  checking for file
'C:\Users\Ad\AppData\Local\Temp\Rtmp06y7wC\remotes2ee87ce24df6\ModelOriented-DALEXtra-625c936/DESCRIPTION'
(454ms)
-  preparing 'DALEXtra': (1.5s)
√  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'DALEXtra_2.1.1.9004.tar.gz'

Warning: package ‘DALEXtra’ is in use and will not be installed

**Comment by Nehagupta90** [comment]
When I run this

remotes::install_github("ModelOriented/DALEXtra")

It gives the following output.

It is recommended to update all of them.
Which would you like to update?

 1: All
 2: CRAN packages only
 3: None
 4: utf8       (1.1.4  -> 1.2.2  ) [CRAN]
 5: cli        (3.1.1  -> 3.2.0  ) [CRAN]
 6: glue       (1.4.1  -> 1.6.2  ) [CRAN]
 7: vctrs      (0.3.8  -> 0.4.0  ) [CRAN]
 8: rlang      (1.0.1  -> 1.0.2  ) [CRAN]
 9: magrittr   (2.0.2  -> 2.0.3  ) [CRAN]
10: fansi      (0.4.1  -> 1.0.3  ) [CRAN]
11: colorspace (1.4-1  -> 2.0-3  ) [CRAN]
12: Rcpp       (1.0.5  -> 1.0.8.3) [CRAN]
13: digest     (0.6.25 -> 0.6.29 ) [CRAN]
14: ggplot2    (3.3.3  -> 3.3.5  ) [CRAN]
15: jsonlite   (1.7.2  -> 1.8.0  ) [CRAN]
16: reticulate (1.18   -> 1.24   ) [CRAN]
17: DALEX      (2.2.1  -> 2.4.0  ) [CRAN]


When I run it (I choose All)

Installing 1 packages: DALEX
Warning: package ‘DALEX’ is in use and will not be installed
WARNING: Rtools is required to build R packages, but is not currently
installed.

Please download and install Rtools 4.0 from
https://cran.r-project.org/bin/windows/Rtools/.

**Comment by maksymiuks** [comment]
You definitely should upgrade DALEX to 2.4.0. Remember that a package cannot be updated if it is loaded. You should restart the session (unload packages) and then update their versions. 

Unfortunately, you don't have Rtools, I highly recommend getting those. 

If it is impossible, try this workaround for the time before DALEXtra gets updated:

```
library("DALEXtra")
explainer <- explain_mlr3(mlr3::as_learner(at), data = df, y = df$price)
```

**Comment by Nehagupta90** [comment]
Thank you maksymiuks

Again the same error when I use explainer <- explain_mlr3(mlr3::as_learner(at),
data = df, y = df$price)

Error: No task stored, and no task provided

When I create the explainer, it gives the following warning, so do you
think the error is hidden here

Preparation of a new explainer is initiated
  -> model label       :  R6  (  default  )
  -> data              :  588  rows  21  cols
  -> target variable   :  588  values
  -> predict function  :  yhat.default will be used (  default  )
  -> predicted values  :  No value for predict function target column. (
 default  )
  -> model_info        :  package Model of class: AutoTuner package
unrecognized , ver. Unknown , task regression (  default  )
  -> predicted values  :  the predict_function returns an error when
executed (  WARNING  )
  -> residual function :  difference between y and yhat (  default  )
  -> residuals         :  the residual_function returns an error when
executed (  WARNING  )

**Comment by hbaniecki** [comment]
Hi @Nehagupta90, could you provide a minimal code example for me to reproduce this error? Then I could try to debug it.

**Comment by Nehagupta90** [comment]
Thank you, I am using the following code and dataset. 

[xerces.csv](https://github.com/ModelOriented/DALEX/files/8513236/xerces.csv)

library(mlr3learners)
library(mlr3extralearners)
library(mlr3tuning)


df= read.csv("xerces.csv")
task=TaskRegr$new("df", df, target = "bug")
learner= lrn("regr.rpart")
resampling = rsmp("repeated_cv", folds=3, repeats=3)
measure= msr("regr.mae")

search_space = paradox::ParamSet$new(
params = list(paradox::ParamDbl$new("cp", lower = 0.001, upper = 0.1)))
terminator = trm("evals", n_evals = 15)

tuner = tnr("grid_search")

at = AutoTuner$new(
learner = learner,
resampling = resampling,
measure = measure,
search_space = search_space,
terminator = terminator,
tuner = tuner, store_tuning_instance = TRUE,
store_benchmark_result = TRUE,
store_models = TRUE
)

at = AutoTuner$new(
  learner = learner,
  resampling = resampling,
  measure = measure,
  search_space = search_space,
  terminator = terminator,
  tuner = tuner,  store_tuning_instance = TRUE,
  store_benchmark_result = TRUE,
  store_models = TRUE 
)

But it gives me the following error when I use

explainer = explain_mlr3(at,
                    data = df[,-21],
                    y = as.numeric(df$bug)-1 ,
                    label="DT")

Error message

Error: No task stored, and no task provided

**Comment by hbaniecki** [comment]
Hi, you did not train the model. Also, character variables cause errors in this case. Hope this code helps:

```r
library(mlr3learners)
library(mlr3extralearners)
library(mlr3tuning)

df= read.csv("xerces.csv")

# character variables cause error
df_subset = df[,-c(1, 2, 3)]

task=TaskRegr$new("df", df_subset, target = "bug")
learner= lrn("regr.rpart")
resampling = rsmp("repeated_cv", folds=3, repeats=3)
measure= msr("regr.mae")

search_space = paradox::ParamSet$new(
  params = list(paradox::ParamDbl$new("cp", lower = 0.001, upper = 0.1)))
terminator = trm("evals", n_evals = 15)

tuner = tnr("grid_search")

at = AutoTuner$new(
  learner = learner,
  resampling = resampling,
  measure = measure,
  search_space = search_space,
  terminator = terminator,
  tuner = tuner, store_tuning_instance = TRUE,
  store_benchmark_result = TRUE,
  store_models = TRUE
)

# you need to fit the model
at$train(task)
at$predict(task)

library(DALEXtra)
explainer = explain_mlr3(at,
                         data = df_subset,
                         y = as.numeric(df$bug)-1 ,
                         label="DT")
predict(at, df_subset)

plot(model_parts(explainer))
```

**Comment by Nehagupta90** [comment]
Thank you again.

Yes, when I exclude the character variables, the explainer work.

Thank you. The issue should be closed.

Best regards
