### ISSUE TITLE
Cannot interepret the Lime explanation with text feature

### ISSUE THREAD

**Issue by Nehagupta90** [ModelOriented/DALEX#497]
Hello, I have a lime explanation for text feature, which I cannot interpret. 

What is the meaning of case1, case2 etc. Also what is 'Explanation fit' 0.54 etc

![image](https://user-images.githubusercontent.com/58039529/163861429-a9ea3b83-81f4-45f2-b140-057cffac4871.png)

**Comment by hbaniecki** [comment]
Hi, I believe you are trying to interpret 4 inputs (observations, cases) at once. The explanation fit should correspond to some measure of the surrogate model's performance, e.g. R^2 of the fitted linear model, which is used to create the explanation. For details, see https://stats.stackexchange.com/a/353668. 

In the future, please redirect questions related to `lime` to the originating project https://github.com/marcotcr/lime.
