### ISSUE TITLE
Instance-level and datasets-level explanation is not consistent

### ISSUE THREAD

**Issue by Nehagupta90** [ModelOriented/DALEX#504]
(1) The randomForest and Ranger models in mlr3 are exactly the same, but still the explanation (instance-level) produced by them have a  slight difference, why this? 

(2) I evaluated individual's instances of a dataset and found that features A, B, and C are constantly appearing as top features but when I apply the permutation-based/dataset level (model_parts) feature importance, I found that features B, A, and D are the top three important features, why this? Is this the limitation of the dataset level explanation that they are not always correct or examining each individual features and then ranking the top/frequent features is not the exact equivalent to this dataset level explanation.

Thank you

**Comment by hbaniecki** [comment]
Hi 
(1) You give no specific information. What do you mean by "exactly the same"? Do the trees in forests have identical variable splits? Which instance-level explanations, e.g. estimation of Shapley Values are based on a random process so it would obviously vary?
(2) There are different methods for estimating instance and dataset level importance of features. This obviously can lead to different rankings of top/frequent features. For consistency, you can use the SHAP framework to compute both: instance-level attributions and then dataset level importance, which bases on those attributions.

**Comment by Nehagupta90** [comment]
Do the trees in forests have identical variable splits? Which
instance-level explanations

I used the default settings so both have the same parameters like number of
trees (n=500 in this case). I used it for the breakdown method but I am
also planning to use the Shap methods and evaluate how the feature
importance for the same data/instance and model is consistent with both
Shap and breakdown methods. There is a small difference of features ranking
achieved with randomForest and Ranger compared to the other models (SVM
etc) but still there is a difference which is strange because randomForest
and Ranger are exactly the same. I evaluated them for the same instance
i.e. the same instance with both randomForest and Ranger, they produce
different rankings.

For dataset level explanation, I used the model_parts() because I do know
if I can use the dataset level features importance with the Shap and
breakdown methods and compare the result with the instance-level features
importance with these Shap and breakdown methods.

**Comment by hbaniecki** [comment]
> randomForest and Ranger are exactly the same

They might be a different implementation of the same random forest algorithm.

> they produce different rankings

In `DALEX`, shap is a random procedure depending on the parameter `B`. So this isn't unexpected.

Please open new issues instead of writing in the closed ones. Thanks
