### ISSUE TITLE
Feature importance with user defined instances

### ISSUE THREAD

**Issue by Nehagupta90** [ModelOriented/DALEX#509]
Can I perform the feature importance on some specific instances ? I have a dataset with output variable having a value of 0/1. I need to produce feature importance/rankings with instances which has output value of 1 only. 

instances_value_One= 1,3,12, 16. 22,34,55, ......

All the instances with output value of 1 is included in this 'instances_value_One' 

I want to use feature importance using model_parts or variable_importance

Is it possible to do this?

**Comment by maksymiuks** [comment]
Are you using R o python version of DALEX?

**Comment by Nehagupta90** [comment]
I am asking the R version.

Thank you

**Comment by hbaniecki** [comment]
Hi, I recommend creating an explainer using a subset of data and then making sure to use `N=None`. For example,

```r
library("DALEX")
library("ranger")

model <- ranger(survived ~., data = titanic_imputed)

instances_value_one <- titanic_imputed$survived==1
data_subset_one <- titanic_imputed[instances_value_one, ]

explainer <- explain(model,
                     data = data_subset_one,
                     y = data_subset_one$survived,
                     label = "Random Forest")


fi <- model_parts(explainer, N=NULL)
plot(fi)
```
