### ISSUE TITLE
Model.frame shouldn't be default training data

### ISSUE THREAD

**Issue by krystian8207** [ModelOriented/DALEX#51]
Hi. 

If `data` parameter is not passed to `explain` function, it is extracted by default from model as `model.frame(data)` (if possible). The assumption here is that `data` should be training data used by model. 
In some cases it's not true. Let's consider
```
model <- glm(log(qsec) ~ exp(drat) + hp, data = mtcars)
```
In here `model.frame(model) ` stores transformed variables, ie. 
```
colnames(model.frame(model)) == c('log(qsec)', 'exp(drat)', 'hp')
```

I think the best way is to use by default:
```
eval(stats::getCall(model)$data)
```

As it uses `envir = parent.frame()` by default it should source training data that was used in model call.

**Comment by pbiecek** [comment]
now the explain() is more verbose and it asks directly for non-training data
