### ISSUE TITLE
PDP with default and optimized settings

### ISSUE THREAD

**Issue by Nehagupta90** [ModelOriented/DALEX#510]
Hello

I want to evaluate the partial dependence profile of a variable with RF model (with default settings) and RF (with optimized settings). Can I do it?

default_model=model_profile(explainer = my_explainer, variables = "var1")
opt_model=model_profile(explainer = my_explainer, variables = "var1")

**Comment by hbaniecki** [comment]
Hi, what exactly do you mean by "evaluate"?

**Comment by Nehagupta90** [comment]
I mean I want to see how the behavior (average values of a variable on the
whole dataset) of a feature is different when we make changes to the data
i.e when we optimize the parameter settings from the default parameter
settings. I want to see if they are consistent with both default and
optimized settings.

Thank you

**Comment by hbaniecki** [comment]
Do you want to compare two explanations in one plot?

**Comment by Nehagupta90** [comment]
Thank you

I have no problem with pdp and I have used it in my previous project. But I
just wanted to know how to plot it with a model both trained with default
settings and optimized settings in one graph.

Best regards

**Comment by hbaniecki** [comment]
Yes, and there you should find many examples of plotting the explanations of two models in one plot.

**Comment by Nehagupta90** [comment]
Thank you again for your useful comments.

Best regards

**Comment by Nehagupta90** [comment]
Yes, something like that, so that users can understand the difference (if
there is any) easily.
