### ISSUE TITLE
plot predict_parts in R gives scatterplot instead of break-down-plot

### ISSUE THREAD

**Issue by MJimitater** [ModelOriented/DALEX#514]
Im using DALEX in R, trying to create a break_down plot from a new observation and a XGBoost model.

I succesfully created the `explain` object and the `predict_parts` break_down dataframe, which BTW took ages (more than a day to calculate - anyone have an intuitive idea why it takes so long or how to speed things up?). 

But plotting the `predict_parts` only gives a scatterplot, I was expecting a nice waterfall-looking plot.

Im sorry for not being able to post a minimal reproducible example and not being able to share data or model, but here ist the snippet:

    library(DALEX)
      
    explain <- DALEX::explain(trained_model, data = train, y = as.numeric(train$PRUEFERGEBNIS)-1, type = "classification", label = "xgboost", predict_function = 
                                  function(trained_model, test){
                                    previous_na_action <- options('na.action')
                                    options(na.action='na.pass')
                                    sparse_matrix_test <- sparse.model.matrix(PRUEFERGEBNIS ~.
                                                                              , data = test)
                                    options(na.action=previous_na_action$na.action)
                                    
                                    results_test <- predict(trained_model, sparse_matrix_test, type = "response")
                                    round(results_test,3)
                                  })

    parts_plot <- predict_parts(explain, new_observation = test[1, , drop = FALSE], type = "break_down")
    plot(parts_plot)

![image](https://user-images.githubusercontent.com/26901261/171191098-15c42d25-a2ba-49e7-ba57-c9be51b59fab.png)

**Comment by hbaniecki** [comment]
Also, what is the output of `predict_parts` really? I mean, check `typeof(parts_plot)`, `class(parts_plot)`, `print(parts_plot)` etc.

**Comment by MJimitater** [comment]
> typeof(parts_plot)
          [1] "list"
          > class(parts_plot)
          [1] "predict_parts" "break_down"    "data.frame"   
          > print(parts_plot)
                                                      contribution
          xgboost: intercept                                 0.581
          xgboost: FZ_BEANTRAGT = 659                       -0.103
          xgboost: FZ_27 = 2                                 0.018
          xgboost: BRUTTOBETRAG_ANTRAG = 1379                0.071
          xgboost: FZ_11 = 0                                -0.098
          xgboost: OSR_R_B_ANZ = 2                           0.009
          xgboost: PK_GEWAERLEISTUNG = 0                     0.047
          xgboost: PK_FZSR_FZS = 0                           0.053
          xgboost: FZ_21 = 0                                -0.022
          xgboost: ABRECHNUNGS_STELLE = 53                  -0.022
          xgboost: FZ_22 = 1                                 0.001
          xgboost: FZ_47 = 0                                -0.006
          xgboost: OF_R_E_ANZ = 0                           -0.010
          xgboost: OSR_R_K_ANZ = 2                           0.000
          xgboost: FZ_13 = 0                                 0.032
          xgboost: USL_R_E_ANZ = 0                          -0.006
          xgboost: PK_VRECHT = 0                             0.005
          xgboost: ALTER_VS = 62                             0.005
          xgboost: FZ_42 = 0                                 0.003
          xgboost: ABSTAND_IN_TAGEN_GEN_VORG = 2862         -0.003
          xgboost: USR_R_E_ANZ = 0                          -0.007
          xgboost: KEINE_AEND_INTAKT_OSL = 5                 0.007
          xgboost: PK_DUBLETTE = 0                           0.002
          xgboost: FZ_46 = 0                                -0.004
          xgboost: KTP_KRANKHAFT_RECHTS = 0                  0.008
          xgboost: BEITRAGSGRUPPE_MAX = 1111                 0.004
          xgboost: PK_RV_UNGUELTIG = 0                      -0.003
          xgboost: PERSONENGRUPPE_MAX = 101                  0.006
          xgboost: OSL_R_E_ANZ = 0                          -0.002
          xgboost: KEINE_AEND_INTAKT_USL = 5                 0.004
          xgboost: FZ_31 = 0                                 0.001
          xgboost: USR_R_B_ANZ = 0                           0.001
          xgboost: USL_R_B_ANZ = 0                           0.002
          xgboost: ANZAHL_VERORD = 56                       -0.006
          xgboost: OF_B_KRANKHAFT_ANZ = 0                    0.004
          xgboost: OSR_B_KRANKHAFT_ANZ = 5                  -0.002
          xgboost: OSR_R_E_ANZ = 0                          -0.001
          xgboost: KRV_KRANKHAFT_RECHTS = 0                  0.004
          xgboost: ABSTAND_IN_TAGEN_VORG = 2862              0.032
          xgboost: PK_GUTACHTERPRAXIS = 0                   -0.001
          xgboost: USR_R_H_ANZ = 0                          -0.002
          xgboost: KRV_KRANKHAFT_LINKS = 1                   0.003
          xgboost: UF_R_E_ANZ = 0                           -0.003
          xgboost: USL_R_H_ANZ = 0                          -0.001
          xgboost: TP_EXISTIERT = 1                          0.000
          xgboost: FZ_64 = 0                                 0.002
          xgboost: PK_BEGUTACHTUNG_EZK = 0                   0.008
          xgboost: KNZ_INTERIMSVERSORGUNG_OK =               0.000
          xgboost: USL_R_K_ANZ = 0                           0.003
          xgboost: PK_BEGUTACHTUNG_FZK = 0                   0.016
          xgboost: KNZ_INTERIMSVERSORGUNG_UK =               0.000
          xgboost: FZ_14 = 0                                 0.002
          xgboost: FZ_44 = 0                                 0.003
          xgboost: VORGAENGER_GEN_ABG = 2                    0.002
          xgboost: USR_R_K_ANZ = 0                           0.003
          xgboost: FZ_12 = 0                                -0.002
          xgboost: PK_BEFUND_UNGUELTIG = 0                  -0.001
          xgboost: UF_B_KRANKHAFT_ANZ = 0                    0.000
          xgboost: UNPLAUSI_AEND_OSL = 0                     0.001
          xgboost: OSR_T_B_ANZ = 2                           0.002
          xgboost: OF_KRV_KRANKHAFT_ANZ = 0                  0.002
          xgboost: FZ_641 = 0                                0.001
          xgboost: KEINE_AEND_INTAKT_USR = 4                 0.000
          xgboost: OSL_B_KRANKHAFT_ANZ = 1                   0.008
          xgboost: PK_FZSR_ZAHNSCHEMA = 0                    0.006
          xgboost: OF_R_K_ANZ = 0                            0.003
          xgboost: KEINE_AEND_INTAKT_OF = 6                  0.002
          xgboost: KEINE_AEND_INTAKT_OSR = 1                -0.001
          xgboost: OF_T_K_ANZ = 0                           -0.002
          xgboost: OF_T_B_ANZ = 0                            0.003
          xgboost: KEINE_AEND_INTAKT_UF = 6                  0.005
          xgboost: FZ_69 = 0                                 0.001
          xgboost: FZ_65 = 0                                 0.001
          xgboost: UF_R_K_ANZ = 0                            0.002
          xgboost: UNPLAUSI_AEND_OSR = 0                     0.000
          xgboost: KEINE_AEND_DEFEKT_USR = 0                 0.000
          xgboost: OSR_R_H_ANZ = 0                           0.000
          xgboost: KEINE_AEND_DEFEKT_OSL = 0                -0.001
          xgboost: FZ_51 = 0                                 0.004
          xgboost: UF_T_T_ANZ = 0                           -0.001
          xgboost: PK_AUSLAND = 0                            0.000
          xgboost: OF_R_H_ANZ = 0                            0.000
          xgboost: FZ_45 = 0                                 0.001
          xgboost: OSL_R_H_ANZ = 0                           0.000
          xgboost: PLAUSI_AEND_OF = 0                        0.000
          xgboost: PK_HAERTEFALL = 0                        -0.001
          xgboost: FZ_41 = 0                                 0.001
          xgboost: UNPLAUSI_AEND_USR = 0                     0.001
          xgboost: USL_T_K_ANZ = 0                           0.001
          xgboost: PLAUSI_AEND_UF = 0                        0.001
          xgboost: FZ_651 = 0                                0.000
          xgboost: UNPLAUSI_AEND_OF = 0                      0.001
          xgboost: PK_FZS7 = 0                               0.000
          xgboost: UNPLAUSI_AEND_USL = 0                     0.000
          xgboost: OF_R_B_ANZ = 0                            0.025
          xgboost: KEINE_AEND_DEFEKT_USL = 0                 0.000
          xgboost: KTP_KRANKHAFT_LINKS = 1                  -0.015
          xgboost: KEINE_AEND_DEFEKT_OSR = 0                 0.000
          xgboost: OSL_T_E_ANZ = 0                           0.001
          xgboost: FZ_62 = 0                                 0.001
          xgboost: OSR_T_E_ANZ = 0                           0.003
          xgboost: FZ_61 = 0                                 0.001
          xgboost: PLAUSI_AEND_USR = 1                       0.000
          xgboost: UF_T_B_ANZ = 0                            0.001
          xgboost: FZ_75 = 0                                 0.001
          xgboost: OF_T_T_ANZ = 0                            0.000
          xgboost: FZ_68 = 0                                 0.002
          xgboost: USR_T_K_ANZ = 0                           0.000
          xgboost: USL_T_B_ANZ = 0                           0.000
          xgboost: XP0002 = NA                               0.001
          xgboost: TAETIGKEITSSCHLUESSEL_MAX = Other         0.001
          xgboost: PK_TP_UNGUELTIG = 0                       0.000
          xgboost: UF_R_H_ANZ = 0                            0.000
          xgboost: FZ_77 = 0                                 0.001
          xgboost: FZ_63 = 0                                 0.000
          xgboost: PK_BEFUND_SW = 0                          0.000
          xgboost: PK_SONSTIGES = 0                          0.001
          xgboost: OF_T_E_ANZ = 0                            0.002
          xgboost: FZ_66 = 0                                 0.001
          xgboost: PK_BEMERKUNG = 0                          0.001
          xgboost: UF_KRV_KRANKHAFT_ANZ = 0                  0.001
          xgboost: FZ_71 = 0                                 0.000
          xgboost: USL_B_KRANKHAFT_ANZ = 2                   0.000
          xgboost: OSR_T_K_ANZ = 2                           0.010
          xgboost: KEINE_AEND_DEFEKT_UF = 0                  0.000
          xgboost: PK_ABLEHNUNG = 0                          0.001
          xgboost: FZ_25 = 0                                 0.000
          xgboost: XP9999 = NA                               0.000
          xgboost: OF_R_P_ANZ = 0                            0.001
          xgboost: PK_BEGUTACHTUNG_BRUECKE = 0               0.000
          xgboost: KEINE_AEND_DEFEKT_OF = 0                  0.000
          xgboost: PLAUSI_AEND_OSR = 4                       0.000
          xgboost: FZ_32 = 0                                 0.002
          xgboost: UNPLAUSI_AEND_UF = 0                      0.000
          xgboost: FZ_74 = 0                                 0.001
          xgboost: FZ_15 = 0                                 0.000
          xgboost: FZ_52 = 0                                 0.000
          xgboost: FZ_54 = 0                                 0.000
          xgboost: FZ_67 = 0                                 0.001
          xgboost: PLAUSI_AEND_USL = 0                       0.000
          xgboost: OSL_R_B_ANZ = 0                           0.001
          xgboost: FZ_72 = 0                                 0.000
          xgboost: OSL_R_K_ANZ = 0                           0.001
          xgboost: PLAUSI_AEND_OSL = 0                      -0.003
          xgboost: OF_KTP_KRANKHAFT_ANZ = 0                  0.000
          xgboost: FZ_73 = 0                                 0.000
          xgboost: OSR_T_H_ANZ = 0                           0.001
          xgboost: OF_T_P_ANZ = 0                            0.001
          xgboost: FZ_48 = 0                                 0.000
          xgboost: OSL_T_K_ANZ = 0                           0.000
          xgboost: OF_R_A_ANZ = 0                            0.000
          xgboost: OSL_T_H_ANZ = 0                           0.000
          xgboost: USR_T_T_ANZ = 0                           0.000
          xgboost: FZ_53 = 0                                 0.000
          xgboost: UF_T_S_ANZ = 0                            0.000
          xgboost: FZ_43 = 0                                 0.002
          xgboost: FZ_610 = 0                                0.000
          xgboost: OF_T_A_ANZ = 0                            0.000
          xgboost: UF_T_H_ANZ = 0                            0.000
          xgboost: USR_B_KRANKHAFT_ANZ = 1                  -0.001
          xgboost: UF_R_T_ANZ = 0                            0.002
          xgboost: UF_R_B_ANZ = 0                            0.003
          xgboost: USR_T_E_ANZ = 0                           0.001
          xgboost: FZ_76 = 0                                 0.000
          xgboost: USL_T_T_ANZ = 0                           0.000
          xgboost: OSL_T_S_ANZ = 0                           0.000
          xgboost: PK_UNFALL = 0                             0.000
          xgboost: UF_T_A_ANZ = 0                            0.000
          xgboost: OSR_T_S_ANZ = 0                           0.001
          xgboost: USL_T_E_ANZ = 0                           0.001
          xgboost: UF_KTP_KRANKHAFT_ANZ = 0                  0.000
          xgboost: USL_T_H_ANZ = 0                           0.001
          xgboost: OSR_T_T_ANZ = 0                           0.000
          xgboost: OF_R_R_ANZ = 0                            0.000
          xgboost: PK_MAT_LAB = 0                            0.000
          xgboost: UF_T_E_ANZ = 0                            0.000
          xgboost: UF_T_P_ANZ = 0                            0.000
          xgboost: OSL_T_B_ANZ = 0                           0.000
          xgboost: USR_T_H_ANZ = 0                           0.001
          xgboost: UF_R_P_ANZ = 0                            0.000
          xgboost: OF_T_S_ANZ = 0                            0.001
          xgboost: OSL_T_T_ANZ = 0                           0.000
          xgboost: PK_BVG = 0                                0.000
          xgboost: PK_BEGUTACHTUNG_BRUECKE2 = 0              0.000
          xgboost: UF_T_K_ANZ = 0                            0.000
          xgboost: USR_T_B_ANZ = 0                           0.001
          xgboost: USL_T_S_ANZ = 0                           0.000
          xgboost: OSL_R_S_ANZ = 0                           0.000
          xgboost: USR_T_S_ANZ = 0                           0.000
          xgboost: OSR_R_S_ANZ = 0                           0.000
          xgboost: UF_R_A_ANZ = 0                            0.000
          xgboost: USL_R_T_ANZ = 0                           0.001
          xgboost: KZ_VORGAENGER_GESAMT_PLANUNG =            0.000
          xgboost: XP0013 = NA                               0.000
          xgboost: OF_R_T_ANZ = 0                            0.004
          xgboost: XP0001 = 0101                             0.000
          xgboost: XP0011 = NA                               0.000
          xgboost: FZ_26 = 0                                 0.000
          xgboost: OF_T_R_ANZ = 0                            0.000
          xgboost: OSR_T_P_ANZ = 0                           0.000
          xgboost: OF_T_H_ANZ = 0                            0.000
          xgboost: USL_R_S_ANZ = 0                           0.000
          xgboost: FZ_24 = 0                                 0.000
          xgboost: MITGL_BEZ_BESONDERHEIT_MAX = 000          0.000
          xgboost: USR_R_S_ANZ = 0                           0.000
          xgboost: FZ_60 = 0                                 0.000
          xgboost: PK_BEGUTACHTUNG_SONSTIGES = 0             0.000
          xgboost: FZ_23 = 0                                 0.000
          xgboost: GESCHLECHT = F                            0.000
          xgboost: OF_R_S_ANZ = 0                            0.000
          xgboost: PK_ZA_AUFFAELLIG = 0                      0.000
          xgboost: UF_R_S_ANZ = 0                            0.000
          xgboost: OSL_T_A_ANZ = 0                           0.000
          xgboost: OSR_T_A_ANZ = 0                           0.000
          xgboost: USR_R_T_ANZ = 0                           0.001
          xgboost: USL_T_R_ANZ = 0                           0.000
          xgboost: PK_DMP = 0                                0.000
          xgboost: FZ_49 = 0                                 0.000
          xgboost: USR_T_P_ANZ = 0                           0.000
          xgboost: UF_T_R_ANZ = 0                            0.000
          xgboost: USL_T_P_ANZ = 0                           0.000
          xgboost: OSR_R_P_ANZ = 0                           0.000
          xgboost: OSL_R_P_ANZ = 0                           0.000
          xgboost: OSL_T_P_ANZ = 0                           0.000
          xgboost: OSL_R_T_ANZ = 0                           0.000
          xgboost: OSR_R_T_ANZ = 0                           0.000
          xgboost: USR_T_A_ANZ = 0                           0.000
          xgboost: USL_T_A_ANZ = 0                           0.000
          xgboost: USL_R_P_ANZ = 0                           0.000
          xgboost: PK_VERTRAGSZA = 0                         0.000
          xgboost: FZ_681 = 0                                0.000
          xgboost: PRUEFERGEBNIS = 1                         0.000
          xgboost: KNZ_BEHANDLUNG_AUSLAND =                  0.000
          xgboost: VORGAENGER_STATUS = 2                     0.000
          xgboost: OSL_R_A_ANZ = 0                           0.000
          xgboost: OSL_R_R_ANZ = 0                           0.000
          xgboost: OSL_T_R_ANZ = 0                           0.000
          xgboost: OSR_R_A_ANZ = 0                           0.000
          xgboost: OSR_R_R_ANZ = 0                           0.000
          xgboost: OSR_T_R_ANZ = 0                           0.000
          xgboost: USL_R_A_ANZ = 0                           0.000
          xgboost: USL_R_R_ANZ = 0                           0.000
          xgboost: UF_R_R_ANZ = 0                            0.000
          xgboost: USR_R_A_ANZ = 0                           0.000
          xgboost: USR_R_P_ANZ = 0                           0.000
          xgboost: USR_R_R_ANZ = 0                           0.000
          xgboost: USR_T_R_ANZ = 0                           0.000
          xgboost: prediction                                0.739

**Comment by hbaniecki** [comment]
Yes, unfortunately, I don't see anything unusual here. You could try using `iBreakDown:::plot.break_down(parts_plot)` or `DALEX:::plot.predict_parts(parts_plot)`. If I got a reproducible example (maybe on a different data/model?), I could try to debug this issue using `debugonce(predict_parts)`.

**Comment by MJimitater** [comment]
Bingo!! I first tried `iBreakdown::plot.break_down(parts_plot)`, but plot.break_down was not an exported object from the namespace. Then I looked for anything in the direction of iBreakdown::plot and and instead found `iBreakdown::plotD3`, which is described as _Plots waterfall break down for objects of break_down class_. Before I could run this function, I needed to additionally install the `r2d3` package. But then finally `iBreakdown::plotD3(parts_plot` resulted in this beautiful breakdown plot:

![grafik](https://user-images.githubusercontent.com/26901261/171802339-554ed32d-0846-4837-989c-41a8ae74badb.png)

So thank you again @hbaniecki for your help on this way, I wouldn't have found the solution without you!

**Comment by hbaniecki** [comment]
Np. @MJimitater, we first implemented `plotD3()` and then created the `modelStudio` package, which makes an interactive dashboard with many visualizations in D3.js. You might want to give it a try https://github.com/ModelOriented/modelStudio, and specifically the `xgboost` example available at https://modelstudio.drwhy.ai/articles/ms-r-python-examples.html#xgboost-dashboard. 

Also, I meant `iBreakdown:::plot.break_down(parts_plot)` with three `:::`, while you used `iBreakdown::plot.break_down(parts_plot)` with two `::`. This is not an exported function by default but is still available to the user (especially to debug the code).

**Comment by MJimitater** [comment]
Thank you @hbaniecki for your fast reply and explanations!! Yes, you were right, `iBreakdown:::plot.break_down(parts_plot)` works too, as well as `DALEX:::plot.predict_parts(parts_plot)`! I overlooked the `:::`.

Your ideas are all VERY helpful!! I will definetly give modelStudio a try! Is there a forum or discussion room for further questions or do you prefer this github issue? BTW congrats for your cool group MI² and for making it open source!

**Comment by hbaniecki** [comment]
I believe GitHub issues are solid, as they appear in Google search when one has a particular issue.
