### ISSUE TITLE
Do XAI tools explain the variance of a model?

### ISSUE THREAD

**Issue by neuideas** [ModelOriented/DALEX#515]
Hello. I have trained a model with 5-folds CV and found that the model has a high variance i.e. performance varies highly across different folds. One fold, for instance, has a mean absolute error of 0.1 and another fold could go to the mean absolute error of 0.5. 

In the existing XAI tools in the Dalex package, can I explore this type of explanation? I mean why the variance go so much for one model and for another model on the same data, has much lower variance. 

Thank you and regards

**Comment by hbaniecki** [comment]
Hi, one idea would be to create a different explainer for each CV and compare their explanations in one plot to see the differences. I would recommend starting from the `model_diagnostics()` function (method if u use Python), which visualizes the residuals of a model per any variable (you can see differences in prediction errors). It would also be useful to compare the feature importance and partial dependence plots for all these models.

**Comment by neuideas** [comment]
Thank you. I am currently using the R version of the Dalex so probably would not work. 

Explainer for each fold seems very interesting, though I cannot recall how I implement it. 

It would also be useful to compare the feature importance and partial dependence plots for all these models.

So you mean first identify the important features and then draw the PD profiles for these features? But how could it helps in identifying the variance in each fold?

**Comment by hbaniecki** [comment]
> Thank you. I am currently using the R version of the Dalex so probably would not work.

I mean, both versions R and Python have the same functionalities needed to perform this: `model_diagnostics()`, `model_parts()`, `model_profile()`.

> Explainer for each fold seems very interesting, though I cannot recall how I implement it.

This I did not understand, I am sorry.

> So you mean first identify the important features and then draw the PD profiles for these features? But how could it helps in identifying the variance in each fold?

I mean: training a model with 5-folds CV involves doing a for loop over these CV folds. So for each iteration create an explainer using `explain()` for this model (and pass `data` as a particular 20% validation set). Then, for each explainer create the above-mentioned explanations and plot all 5 explanations together.

**Comment by neuideas** [comment]
I mean: training a model with 5-folds CV involves doing a for loop over
these CV folds. So for each iteration create an explainer using explain() for
this model (and pass data as a particular 20% validation set). Then, for
each explainer create the above-mentioned explanations and plot all 5
explanations together.

Thank you, I am now understanding your point. I am trying to evaluate this
aspect and if it works, it will be very interesting because many
researchers in my area talk about the "variance of the model's performance"
but no work is done to mitigate it.

Best regards
