### ISSUE TITLE
Can DALEX::explain() operate on a subset of predictors?

### ISSUE THREAD

**Issue by n8layman** [ModelOriented/DALEX#528]
I'm working with a gam distributed lag model which has requires two matrix columns. The first is a matrix of the number of days lagged back (`lags`) and the second is the lagged values (`lagged_vals`) themselves. It's just part of the way distributed lag models work in mgcv. When creating an explainer though, it would be nice to pass `lags` on to the `predict_function` but _exclude_ them from the set of predictors that get evaluated by `DALEX`. Is there a way to do that? In other words can DALEX::explain() do its thing on only a subset of the predictors and pass the others on un-modified to the newdata argument of the predict function?

**Comment by hbaniecki** [comment]
Hi @n8layman, I might be able to help but would require a short code example of the mgcv lag model. It can use a toy dataset.
