### ISSUE TITLE
arena and http from external IP

### ISSUE THREAD

**Issue by MLud** [ModelOriented/DALEX#530]
Hi,
How I can use a arena.drwhy.ai platform when I don't have https endpoint which serves dx.Arena object by:
arena.run_server(disable_logs=False, port=8181,host='0.0.0.0')

I got this info in web browser:
vue-resource.esm.js:996 Mixed Content: The page at 'https://arena.drwhy.ai/?data=http://xx.xx.xx.xx:8181/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://xx.xx.xx.xx:8181/'. This request has been blocked; the content must be served over HTTPS.

**Comment by piotrpiatyszek** [comment]
Hey, change the URL in the browser from https://arena.drwhy.ai/?data=http://xx.xx.xx.xx:8181/ to http://arena.drwhy.ai/?data=http://xx.xx.xx.xx:8181/.

**Comment by MLud** [comment]
works, thx
