### ISSUE TITLE
collinearity issue in permutation based feature importance (technical question)

### ISSUE THREAD

**Issue by asheetal** [ModelOriented/DALEX#533]
I use DALEX in most of my ML research projects.  I keep getting a criticism from reviewers regarding a drawback of permutation based method in the presence of multiple correlated predictors. They argue that if there is a group of highly correlated but important predictors, they may not show up at the top of feature importance. Can someone comment on this criticism? How is this addressed in DALEX?

**Comment by asheetal** [comment]
Thanks for responding back. Yes grouped feature importance is one way to check all correlated features all at once. But I do not know which features are correlated. I am only looking at individual item level predictors. Would that be a problem in DALEX? If so, how can I minimize the effect of correlation between unknown predictors?

**Comment by hbaniecki** [comment]
> But I do not know which features are correlated. I am only looking at individual item level predictors.

I believe this is what the `triplot` tool aims to overcome. See the exemplary plot visualizing: (left) local feature importance, (right) feature correlation structure, and (middle) combined importance for groups of correlated features.

1. `triplot` in Python https://dalex.drwhy.ai/python-dalex-aspect.html
2. `triplot` in R https://github.com/ModelOriented/triplot 

![image](https://user-images.githubusercontent.com/32574004/205495748-934496a6-51a1-43fb-9557-c89c1052de11.png)

**Comment by asheetal** [comment]
So seems like this might be useful for me. So in a nutshell I do need to look at correlated variables before determining which is the most important predictor in the model. Would this be the correct statement?

**Comment by pbiecek** [comment]
correct, 
importance of correlated feature is a tricky question,
for PDP/ALE profile an interesting discussion about this is also in https://rss.onlinelibrary.wiley.com/doi/10.1111/rssb.12377 and  https://ema.drwhy.ai/accumulatedLocalProfiles.html 

for variable importance the triplot helps to compare importance of individual variables as well as groups of correlated variables

**Comment by asheetal** [comment]
Thanks @pbiecek 
I tried to follow the ALEplot paper (Apley and Zhu, 2019). I get that PDP plots are not authoritative in the presence of collinearity and we should prefer ALE plots. What is still not clear is how ALE links with model variable importance and the effect collinearity will have on model variable importance. As an applied data scientist, I am just interested in top 5 important features out of approximately 1000 features and use those 5 for a subsequent field experiment. I cannot vary more than 5 in a field experiment.

**Comment by hbaniecki** [comment]
@asheetal 
> What is still not clear is how ALE links with model variable importance

ALE/PDP link indirectly to variable importance. For example, see our work on Variable importance via oscillations https://github.com/modeloriented/vivo and Variance-based variable importance [Greenwell et al. (2018)](https://arxiv.org/abs/1805.04755) and [Scholbeck et al. (2019)](https://arxiv.org/abs/1904.03959) with code at https://github.com/koalaverse/vip.

> If Molnar's approach of "conditional subgroup" is the way forward. Is there a code snippet that I can follow?

I can link to the code from the article https://github.com/christophM/paper_conditional_subgroups

I hope all the resources given in this issue can guide you in your experiments.

**Comment by hbaniecki** [comment]
seems answered, reopen if needed :-)
