### ISSUE TITLE
Fairness module: why using those specific checks, while omitting others?

### ISSUE THREAD

**Issue by ronnee19** [ModelOriented/DALEX#534]
Hi, I am using your fairness package for my project, and I wondered about your fairness checks:

For the test equal opportunity ratio, you use TPR, not FNR (the True ratio and not the complementary False ratio).
but,
For the test "predictive equality ratio" you use FPR, not TNR (the False ratio, not the complementary True ratio).

I wondered what is the justification for TPR and FPR specifically (and not TPR and TNR for example).
Thanks!

**Comment by jakwisn** [comment]
Hi, 
It comes straight from the mathematical definitions of those metrics. You can learn about those in detail in [our paper](https://rjournal.github.io/articles/RJ-2022-019/).  But in general for example for _equal opportunity_ you are conditioning the Y_hat = 1 by Y = 1 which is the definition of TPR:

![image](https://user-images.githubusercontent.com/43787962/209571483-b70625ce-e25f-4248-855d-f52e3f4f7e33.png)


However, one interesting property is that when a predictor perfectly satisfies _equal opportunity_ - both TPR and FNR should be equal in both subgroups. 

The respective thing happens in _predictive equality ratio_. 

Let me know if this answers your question

**Comment by hbaniecki** [comment]
Considering this answered; reopen if needed.
