### ISSUE TITLE
Differences between performance metrics between ranger model and its explain

### ISSUE THREAD

**Issue by ManuelSpinola** [ModelOriented/DALEX#561]
I see there are differences for the metrics performance between a ranger model and its explain. Why is that?

aps_ranger <- ranger::ranger(m2.price~., data = apartments, num.trees = 50)

aps_ranger
Ranger result

Call:
 ranger::ranger(m2.price ~ ., data = apartments, num.trees = 50) 

Type:                             Regression 
Number of trees:                  50 
Sample size:                      1000 
Number of independent variables:  5 
Mtry:                             2 
Target node size:                 5 
Variable importance mode:         none 
Splitrule:                        variance 
OOB prediction error (MSE):       93997.56 
R squared (OOB):                  0.8856602 

exp_ranger <- explain(aps_ranger, data = apartments, y = apartments$m2.price)

mod_per <- model_performance(exp_ranger)

mod_per
Measures for:  regression
mse        : 21442.99 
rmse       : 146.4342 
r2         : 0.9738904 
mad        : 84.57676

Residuals:
         0%         10%         20%         30% 
-491.535000 -160.125376 -109.455093  -75.266200 
        40%         50%         60%         70% 
 -43.538133  -20.939611    8.850819   47.124000 
        80%         90%        100% 
  97.417832  197.996033  759.546667

**Comment by mayer79** [comment]
The metrics of ranger are calculated from out-of-bag predictions, those of DALEX on the data provided.

Note that it basically never makes sense to study random forest performance (non-oob) on the training data except to demonstrate its massive overfit.
