### ISSUE TITLE
error on plot predict_parts duplicate row names

### ISSUE THREAD

**Issue by jamesburnsTTRS** [ModelOriented/DALEX#562]
> explainer_2 <- explain_xgboost(clf, data = newmat, y=Weekly_SL_Agg$LN_SWP_Act)
Preparation of a new explainer is initiated
  -> model label       :  xgb.Booster  (  default  )
  -> data              :  378  rows  49  cols 
  -> target variable   :  378  values 
  -> predict function  :  yhat.xgb.Booster  will be used (  default  )
  -> predicted values  :  No value for predict function target column. (  default  )
  -> model_info        :  package xgboost , ver. 1.7.6.1 , task regression (  default  ) 
  -> predicted values  :  numerical, min =  zz.373191 , mean =  kk.75155 , max =  aa.02619  
  -> residual function :  difference between y and yhat (  default  )
  -> residuals         :  numerical, min =  -z.7959752 , mean =  -b.000319823 , max =  f.2809396 
The model works 
> plot(predict_parts(explainer_2,newmat))
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning message:
non-unique value when setting 'row.names': ‘xgb.Booster’ 

first variable is a predictor 1 week of Black Friday 0 elsewhere for 378 rows of weekly data
and I think that's what's driving this error or do you need to create x axis per variable

there are many variables with dupes per month since many are monthly figures. Do you need to create a separate x axis per variable vs a row id common for all?

**Comment by maksymiuks** [comment]
Hi, 

could you please share some dummy data example so we can reproduce the issue?

**Comment by jamesburnsTTRS** [comment]
sure new error on dummy data
> explainer_2 <- explain_xgboost(clf, data = newmatRand,y=XG_Data_Rand$target)
Preparation of a new explainer is initiated
  -> model label       :  xgb.Booster  (  default  )
  -> data              :  378  rows  46  cols 
  -> data              :  rownames to data was added ( from 1 to 378 ) 
  -> target variable   :  378  values 
  -> predict function  :  yhat.xgb.Booster  will be used (  default  )
  -> predicted values  :  No value for predict function target column. (  default  )
  -> model_info        :  package xgboost , ver. 1.7.6.1 , task regression (  default  ) 
  -> predicted values  :  numerical, min =  0.6814117 , mean =  5.276236 , max =  9.172926  
  -> residual function :  difference between y and yhat (  default  )
  -> residuals         :  numerical, min =  -6.374471 , mean =  0.142439 , max =  6.54051  
  A new explainer has been created!  
> plot(predict_parts(explainer_2,newmatRand))
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning message:
non-unique value when setting 'row.names': ‘xgb.Booster’ 
[XG_Data_Send.xlsx](https://github.com/ModelOriented/DALEX/files/14895493/XG_Data_Send.xlsx)

**Comment by jamesburnsTTRS** [comment]
Thanks for the quick response! I think I figured it out. All the parameters were zero and the forecasts were the intercept. I looked at the file created by predict_parts(explainer, data). How did you build that file and what are the various sections?Sent from my iPhoneOn Apr 6, 2024, at 4:32 PM, maksymiuks ***@***.***> wrote:﻿
Hi,
could you please share some dummy data example so we can reproduce the issue?
