### ISSUE TITLE
Does DALEX work with PyTorch models?

### ISSUE THREAD

**Issue by yanghuikang** [ModelOriented/DALEX#565]
I've been using DALEX to make ALE profiles for xgboost models, and recently want to test neural networks. I see that tensorflow is supported and wonder if there is a way to use it with PyTorch.

**Comment by hbaniecki** [comment]
Hi, `dalex` will work with any model for which you can pass a `predict_function` that inputs model with data in `np.ndarray` and returns a 1-dimensional `np.ndarray` with model predictions. Examples of such predict functions: https://github.com/ModelOriented/DALEX/blob/master/python/dalex/dalex/_explainer/yhat.py

Notably, for tensorflow, it looks like this:
```python
def yhat_tf_regression(m, d):
    return m.predict(np.array(d), verbose=0).reshape(-1, )

def yhat_tf_classification(m, d):
    return m.predict(np.array(d), verbose=0)[:, 1]
```

**Comment by yanghuikang** [comment]
Thank you very much! I will test it with PyTorch.

**Comment by hbaniecki** [comment]
reopen if needed
