### ISSUE TITLE
Compatibility with >= Numpy 2.0.0 (update of ptp method)

### ISSUE THREAD

**Issue by Chip2916** [ModelOriented/DALEX#571]
Hey Dalex team!

Working on a package that has Dalex and Numpy as dependencies and have encountered an issue when using Dalex with >= Numpy 2.0.0.

When calling VariableImportance.plot() an error is raised (see below) due to the use of dl.ptp() [here](https://github.com/ModelOriented/DALEX/blob/28a936b067abad5c3a3ff11b8a6b7a4bfdab1db8/python/dalex/dalex/model_explanations/_variable_importance/object.py#L201).

This is also present in other scripts such as AggregatedProfiles.plot() [here](https://github.com/ModelOriented/DALEX/blob/28a936b067abad5c3a3ff11b8a6b7a4bfdab1db8/python/dalex/dalex/model_explanations/_aggregated_profiles/object.py#L245)

use of array.ptp() throughout the package would need to be replaced by np.ptp(array) to be compatible with latest numpy versions. _This fix should not cause any issues for those who are still using numpy < 2.0.0._

**Error:** 

![image](https://github.com/user-attachments/assets/6c82729b-e88c-447c-8551-d419b73a2a86)

**Numpy Doc**

As per the [numpy migration guide](https://numpy.org/devdocs/numpy_2_0_migration_guide.html) certain methods have been replaced. One of them being array.ptp() being replaced by np.ptp(array)

![image](https://github.com/user-attachments/assets/7123884e-29a4-4e4c-ad53-af60563a90e7)

**Comment by hbaniecki** [comment]
Hi @Chip2916 , big thanks for raising this issue. I shall fix this ASAP (or feel free to contribute a PR with changes like `x.ptp()` -> `np.ptp(x)`)

**Comment by Chip2916** [comment]
No problem, PR raised  - also replaced instances of np.Inf with np.inf as latest Numpy releases removed use of np.Inf as part of change to namespaces to avoid multiple ways to access same attribute

**Comment by hbaniecki** [comment]
Thank you! A new `dalex` v1.7.1 with the fix is now on PyPI.
