### ISSUE TITLE
variable_importance, dropout loss not highest for baseline

### ISSUE THREAD

**Issue by Vidaringa** [ModelOriented/DALEX#63]
Hello,

I'm not sure if this is a problem or not. But I'm using variable_importance for my cubist regression model. I've never seen this before but the basesline dropout loss is not at the top of the graph.

What does this mean?

![image](https://user-images.githubusercontent.com/20194883/55002493-97ca8500-4fce-11e9-8bef-d4170b552d56.png)

**Comment by pbiecek** [comment]
Would you share an example with R code?
It looks like gengi_4c is transformed and permutations in this variable affect loss more than permutations in y
