### ISSUE TITLE
DALEX and MLJar

### ISSUE THREAD

**Issue by pbiecek** [ModelOriented/DALEX#69]
Use DALEX to explain AutoML model created with MLJar
like this one:
https://mljar.com/blog/machine-learning-wars/

**Comment by pbiecek** [comment]
@maksymiuks what do you think about adding MLJar suppoer for DALEXtra?

**Comment by maksymiuks** [comment]
Very nice idea, it is added:

https://github.com/ModelOriented/DALEXtra/blob/master/R/explain_mljar.R
