### ISSUE TITLE
New support for scikitlearn models

### ISSUE THREAD

**Issue by maksymiuks** [ModelOriented/DALEX#86]

**Comment by pbiecek** [comment]
I have following error
```
> model <- scikitlearn_model(system.file("extdata", "gbm.pkl", package = "DALEX"))
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: unsupported pickle protocol: 3 
```

I have following version of reticulate

```
    reticulate    * 1.10    2018-08-05 [1] CRAN (R 3.5.0)
```

**Comment by pbiecek** [comment]
I guess that you need to dump model with lower version as in 
https://stackoverflow.com/questions/25843698/valueerror-unsupported-pickle-protocol-3-python2-pickle-can-not-load-the-file

**Comment by maksymiuks** [comment]
Thanks for that!

Problem is connected with file provided for tests. Function itself is not corrupted.

**Comment by pbiecek** [comment]
Now I have
```
Error in py_call_impl(callable, dots$args, dots$keywords): ValueError: non-string names in Numpy dtype unpickling
```

it may be this: https://stackoverflow.com/questions/49075045/valueerror-non-string-names-in-numpy-dtype-unpickling-only-on-aws-lambda

what version of sklearn do you have?

**Comment by pbiecek** [comment]
this feature is moved to DALEXtra
