### ISSUE TITLE
Add option for silent execution

### ISSUE THREAD

**Issue by kamilsi** [ModelOriented/DALEX#94]
Almost all DALEX functions involve plenty of progress bars as part of the output. This is nice when you work interactively, but it doesn't look very good in notebooks. It would be great to have a feature to perform silent computation. Or maybe at least make them messages (which might be easily ignored in notebooks)

**Comment by pbiecek** [comment]
Thanks, 
which functions you are referring to?
I do not recall progress bars.

**Comment by kamilsi** [comment]
You are right - I assumed it came from DALEX, but actually it came from the classifier.
