### ISSUE TITLE
Calculating residuals in explain() do not handle factors

### ISSUE THREAD

**Issue by agosiewska** [ModelOriented/DALEX#99]
```
library(DALEX)
data(titanic)
titanic <- na.omit(titanic)
model_glm <- glm(survived ~ ., family = binomial, data = titanic)
exp_glm <- explain(model_glm, data = titanic, y = titanic$survived)
exp_glm$residuals
```
returns NAs

The reason is that actual response (`titanic$survived`) is a factor. Would it be possible to handle this? Maybe by adding `as.numeric()` somewhere ;)

**Comment by maksymiuks** [comment]
Hello,

Actually, we have a warning for such behaviour, and it can be seen here:
https://github.com/ModelOriented/DALEX/blob/master/R/explain.R#L108-L112

Answer why we cannot act for user is that we don't know which factor should be zero and which should be 1.

**Comment by agosiewska** [comment]
ok, thanks :)
